const ApiConstants = {
  API_LOGIN_LOAD: "API_LOGIN_LOAD",
  API_LOGIN_SUCCESS: "API_LOGIN_SUCCESS",
  API_LOGIN_FAIL: "API_LOGIN_FAIL",
  API_LOGIN_ERROR: "API_LOGIN_ERROR",

  API_ROLE_LOAD: "API_ROLE_LOAD",
  API_ROLE_SUCCESS: "API_ROLE_SUCCESS",
  API_ROLE_FAIL: "API_ROLE_FAIL",
  API_ROLE_ERROR: "API_ROLE_ERROR",

  API_URE_LOAD: "API_URE_LOAD",
  API_URE_SUCCESS: "API_URE_SUCCESS",
  API_URE_FAIL: "API_URE_FAIL",
  API_URE_ERROR: "API_URE_ERROR",

  MENU_NAVIGATION_CHANGE: "MENU_NAVIGATION_CHANGE",

  ///////registration reducer
  API_REGISTRATION_FAIL: "API_REGISTRATION_FAIL",
  API_REGISTRATION_ERROR: "API_REGISTRATION_ERROR",

  /////registration competition list
  API_REG_COMPETITION_LIST_LOAD: "API_REG_COMPETITION_LIST_LOAD",
  API_REG_COMPETITION_LIST_SUCCESS: "API_REG_COMPETITION_LIST_SUCCESS",

  /////registration competition list
  API_REG_MEMBERSHIP_LIST_LOAD: "API_REG_MEMBERSHIP_LIST_LOAD",
  API_REG_MEMBERSHIP_LIST_SUCCESS: "API_REG_MEMBERSHIP_LIST_SUCCESS",

  /////registration competition list delete product
  API_REG_COMPETITION_LIST_DELETE_LOAD: "API_REG_COMPETITION_LIST_DELETE_LOAD",
  API_REG_COMPETITION_LIST_DELETE_SUCCESS:
    "API_REG_COMPETITION_LIST_DELETE_SUCCESS",

  /////registration membership list delete product
  API_REG_MEMBERSHIP_LIST_DELETE_LOAD: "API_REG_MEMBERSHIP_LIST_DELETE_LOAD",
  API_REG_MEMBERSHIP_LIST_DELETE_SUCCESS:
    "API_REG_MEMBERSHIP_LIST_DELETE_SUCCESS",

  ///////app reducer
  API_APP_FAIL: "API_APP_FAIL",
  API_APP_ERROR: "API_APP_ERROR",

  //registration form Save
  API_REG_FORM_LOAD: "API_REG_FORM_LOAD",
  API_REG_FORM_SUCCESS: "API_REG_FORM_SUCCESS",

  //registration Form Venue get

  API_REG_FORM_VENUE_LOAD: "API_REG_FORM_VENUE_LOAD",
  API_REG_FORM_VENUE_SUCCESS: "API_REG_FORM_VENUE_SUCCESS",

  //registration Form Advanced Settings
  API_REG_FORM_SETTINGS_LOAD: "API_REG_FORM_SETTINGS_LOAD",
  API_REG_FORM_SETTINGS_SUCCESS: "API_REG_FORM_SETTINGS_SUCCESS",

  //registration Form Advanced Settings
  API_REG_FORM_METHOD_LOAD: "API_REG_FORM_METHOD_LOAD",
  API_REG_FORM_METHOD_SUCCESS: "API_REG_FORM_METHOD_SUCCESS",

  // registration form MEMBERSHIP_PRODUCT list
  API_REG_FORM_MEMBERSHIP_PRODUCT_LOAD: "API_REG_FORM_MEMBERSHIP_PRODUCT_LOAD",
  API_REG_FORM_MEMBERSHIP_PRODUCT_SUCCESS:
    "API_REG_FORM_MEMBERSHIP_PRODUCT_SUCCESS",

  //Get registration Form
  API_GET_REG_FORM_LOAD: "API_GET_REG_FORM_LOAD",
  API_GET_REG_FORM_SUCCESS: "API_GET_REG_FORM_SUCCESS",

  //update registration form
  API_UPDATE_REG_FORM_LOAD: "API_UPDATE_REG_FORM_LOAD",
  API_UPDATE_REG_FORM_SUCCESS: "API_UPDATE_REG_FORM_SUCCESS",

  //clear particular reducer data
  REG_CLEARING_PARTICULAR_REDUCER_DATA: "REG_CLEARING_PARTICULAR_REDUCER_DATA",

  /////registration get membership product details
  API_REG_GET_MEMBERSHIP_PRODUCT__LOAD: "API_REG_GET_MEMBERSHIP_PRODUCT_LOAD",
  API_REG_GET_MEMBERSHIP_PRODUCT_SUCCESS:
    "API_REG_GET_MEMBERSHIP_PRODUCT_SUCCESS",

  /////registration save membership product details
  API_REG_SAVE_MEMBERSHIP_PRODUCT__LOAD: "API_REG_SAVE_MEMBERSHIP_PRODUCT_LOAD",
  API_REG_SAVE_MEMBERSHIP_PRODUCT_SUCCESS:
    "API_REG_SAVE_MEMBERSHIP_PRODUCT_SUCCESS",

  /////get the common year list reference
  API_YEAR_LIST__LOAD: "API_YEAR_LIST__LOAD",
  API_YEAR_LIST_SUCCESS: "API_YEAR_LIST_SUCCESS",
  API_ONLY_YEAR_LIST__LOAD: "API_ONLY_YEAR_LIST__LOAD",
  API_ONLY_YEAR_LIST_SUCCESS: "API_ONLY_YEAR_LIST_SUCCESS",

  /////get the common membership product validity type list reference
  API_PRODUCT_VALIDITY_LIST__LOAD: "API_PRODUCT_VALIDITY_LIST__LOAD",
  API_PRODUCT_VALIDITY_LIST_SUCCESS: "API_PRODUCT_VALIDITY_LIST_SUCCESS",

  /////get the common Competition type list reference
  API_COMPETITION_TYPE_LIST__LOAD: "API_COMPETITION_TYPE_LIST__LOAD",
  API_COMPETITION_TYPE_LIST_SUCCESS: "API_COMPETITION_TYPE_LIST_SUCCESS",

  ///////////get the default membership  product types in registartion membership fees
  API_REG_GET_DEFAULT_MEMBERSHIP_PRODUCT_TYPES__LOAD:
    "API_REG_GET_DEFAULT_MEMBERSHIP_PRODUCT_TYPES__LOAD",
  API_REG_GET_DEFAULT_MEMBERSHIP_PRODUCT_TYPES_SUCCESS:
    "API_REG_GET_DEFAULT_MEMBERSHIP_PRODUCT_TYPES_SUCCESS",

  /////registration save membership product Fees
  API_REG_SAVE_MEMBERSHIP_PRODUCT_FEES__LOAD:
    "API_REG_SAVE_MEMBERSHIP_PRODUCT_FEES_LOAD",
  API_REG_SAVE_MEMBERSHIP_PRODUCT_FEES_SUCCESS:
    "API_REG_SAVE_MEMBERSHIP_PRODUCT_FEES_SUCCESS",

  /////registration save membership product Discount
  API_REG_SAVE_MEMBERSHIP_PRODUCT_DISCOUNT__LOAD:
    "API_REG_SAVE_MEMBERSHIP_PRODUCT_DISCOUNT_LOAD",
  API_REG_SAVE_MEMBERSHIP_PRODUCT_DISCOUNT_SUCCESS:
    "API_REG_SAVE_MEMBERSHIP_PRODUCT_DISCOUNT_SUCCESS",

  /////get the common Membership Product Fees Type
  API_COMMON_MEMBERSHIP_PRODUCT_FEES_TYPE__LOAD:
    "API_COMMON_MEMBERSHIP_PRODUCT_FEES_TYPE__LOAD",
  API_COMMON_MEMBERSHIP_PRODUCT_FEES_TYPE_SUCCESS:
    "API_COMMON_MEMBERSHIP_PRODUCT_FEES_TYPE_SUCCESS",

  //////chnage the membership fees table data
  CHANGE_MEMBERSHIP_FEES_TABLE_INPUT: "CHANGE_MEMBERSHIP_FEES_TABLE_INPUT",

  /////get the common discount Type
  API_COMMON_DISCOUNT_TYPE__LOAD: "API_COMMON_DISCOUNT_TYPE__LOAD",
  API_COMMON_DISCOUNT_TYPE_SUCCESS: "API_COMMON_DISCOUNT_TYPE_SUCCESS",

  /////get the membership product discount Types
  API_MEMBERSHIP_PRODUCT_DISCOUNT_TYPE__LOAD:
    "API_MEMBERSHIP_PRODUCT_DISCOUNT_TYPE__LOAD",
  API_MEMBERSHIP_PRODUCT_DISCOUNT_TYPE_SUCCESS:
    "API_MEMBERSHIP_PRODUCT_DISCOUNT_TYPE_SUCCESS",

  //////add new membership type in the membership fees section
  ADD_NEW_MEMBERSHIP_TYPE: "ADD_NEW_MEMBERSHIP_TYPE",

  //for clear competition data
  API_CLEAR_COMPETITION: "API_CLEAR_COMPETITION",

  //for change membership category
  REG_FORM_UPDATE_MEMBERSHIP_CATEGORY: "REG_FORM_UPDATE_MEMBERSHIP_CATEGORY",

  ////add another discount in the membership fees
  ADD_ANOTHER_DISCOUNT_MEMBERSHIP_FEES: "ADD_ANOTHER_DISCOUNT_MEMBERSHIP_FEES",

  ///updated discount in membership fees section
  UPDATE_DISCOUNT_DATA_MEMBERSHIP_FEES: "UPDATE_DISCOUNT_DATA_MEMBERSHIP_FEES",

  ////membership fees radip apply fees on change
  ON_CHANGE_RADIO_APPLY_FEES_MEMBERSHIP_FEES: "ON_CHANGE_RADIO_APPLY_FEES_MEMBERSHIP_FEES",

  ////age mandate and membershipTypes onchange selection checkbox
  ON_CHANGE_SELECTION_MEM_TYPE_AGE_MANDATE_CHECKBOX: "ON_CHANGE_SELECTION_MEM_TYPE_AGE_MANDATE_CHECKBOX",

  ///////onchange date data in age restriction in the membership types
  ON_CHANGE_DATE_AGE_MANDATE_MEMBERSHIP_TYPES: "ON_CHANGE_DATE_AGE_MANDATE_MEMBERSHIP_TYPES",


  API_MEMBERSHIP_PRODUCT_DISCOUNT_TYPE__LOAD: "API_MEMBERSHIP_PRODUCT_DISCOUNT_TYPE__LOAD",
  API_MEMBERSHIP_PRODUCT_DISCOUNT_TYPE_SUCCESS: "API_MEMBERSHIP_PRODUCT_DISCOUNT_TYPE_SUCCESS",




  ////remove custom membership type from the membership fees
  REMOVE_CUSTOM_MEMBERSHIP_FEES_TYPE: "REMOVE_CUSTOM_MEMBERSHIP_FEES_TYPE",


  REG_FORM_UPDATE_MEMBERSHIP_PRODUCT_TYPES:
    "REG_FORM_UPDATE_MEMBERSHIP_PRODUCT_TYPES",

  REG_FORM_UPDATE_MEMBERSHIP_REGISTRATIONLOCK:
    "REG_FORM_UPDATE_MEMBERSHIP_REGISTRATIONLOCK",

  REG_FORM_UPDATE_DISCLAIMER_TEXT: "REG_FORM_UPDATE_DISCLAIMER_TEXT",

  REG_FORM_CHECKED_VISIBLE: "REG_FORM_CHECKED_VISIBLE",


  ////Goal List
  API_LIVE_SCORE_GOAL_LIST_LOAD: "API_LIVE_SCORE_GOAL_LIST_LOAD",
  API_LIVE_SCORE_GOAL_LIST_SUCCESS: "API_LIVE_SCORE_GOAL_LIST_SUCCESS",
  API_LIVE_SCORE_GOAL_LIST_FAIL: "API_LIVE_SCORE_GOAL_LIST_FAIL",
  API_LIVE_SCORE_GOAL_LIST_ERROR: "API_LIVE_SCORE_GOAL_LIST_ERROR",


  REG_FORM_REPLY_CHECKED_VISIBLE: "REG_FORM_REPLY_CHECKED_VISIBLE",

  /**********competition fee Api constatnts */

  ///////competition feees
  API_COMPETITION_FEES_FAIL: "API_COMPETITION_FEES_FAIL",
  API_COMPETITION_FEES_ERROR: "API_COMPETITION_FEES_ERROR",

  // init api for reference in competition fee
  API_REG_COMPETITION_FEE_INIT_LOAD: "API_REG_COMPETITION_FEE_INIT_LOAD",
  API_REG_COMPETITION_FEE_INIT_SUCCESS: "API_REG_COMPETITION_FEE_INIT_SUCCESS",

  /////get the competition fees all the data in one API
  API_GET_COMPETITION_FEES_DETAILS_LOAD: "API_GET_COMPETITION_FEES_DETAILS_LOAD",
  API_GET_COMPETITION_FEES_DETAILS_SUCCESS: "API_GET_COMPETITION_FEES_DETAILS_SUCCESS",

  ///save the competition fees details
  API_SAVE_COMPETITION_FEES_DETAILS_LOAD: "API_SAVE_COMPETITION_FEES_DETAILS_LOAD",
  API_SAVE_COMPETITION_FEES_DETAILS_SUCCESS: "API_SAVE_COMPETITION_FEES_DETAILS_SUCCESS",

  ////save the competition membership tab details
  API_SAVE_COMPETITION_FEES_MEMBERHSIP_TAB_LOAD: "API_SAVE_COMPETITION_FEES_MEMBERHSIP_TAB_LOAD",
  API_SAVE_COMPETITION_FEES_MEMBERHSIP_TAB_SUCCESS: "API_SAVE_COMPETITION_FEES_MEMBERHSIP_TAB_SUCCESS",

  ////get default competition membershipproduct tab details
  API_GET_DEFAULT_COMPETITION_FEES_MEMBERHSIP_PRODUCT_LOAD: "API_GET_DEFAULT_COMPETITION_FEES_MEMBERHSIP_PRODUCT_LOAD",
  API_GET_DEFAULT_COMPETITION_FEES_MEMBERHSIP_PRODUCT_SUCCESS: "API_GET_DEFAULT_COMPETITION_FEES_MEMBERHSIP_PRODUCT_SUCCESS",

  ////membership product selected action tochange membership typearray data
  COMPETITION_FEES_MEMBERSHIP_PRODUCT_SELECTED_ONCHANGE: "COMPETITION_FEES_MEMBERSHIP_PRODUCT_SELECTED_ONCHANGE",

  ////membership types in competition fees onchhange function
  COMPETITION_FEES_MEMBERSHIP_TYPES_SELECTED_ONCHANGE: "COMPETITION_FEES_MEMBERSHIP_TYPES_SELECTED_ONCHANGE",

  /////save the division table data  in the competition fees section
  API_SAVE_COMPETITION_FEES_DIVISION_TAB_LOAD: "API_SAVE_COMPETITION_FEES_DIVISION_TAB_LOAD",
  API_SAVE_COMPETITION_FEES_DIVISION_TAB_SUCCESS: "API_SAVE_COMPETITION_FEES_DIVISION_TAB_SUCCESS",

  /////onchange the division table data on change
  COMPETITION_FEES_DIVISION_TABLE_DATA_ONCHANGE: "COMPETITION_FEES_DIVISION_TABLE_DATA_ONCHANGE",

  //////add or remove another division inthe divsision tab
  COMPETITION_FEES_DIVISION_ADD_REMOVE: "COMPETITION_FEES_DIVISION_ADD_REMOVE",


  //update competition fee payment  charity round up
  UPDATE_PAYMENTS_COMPETITION_FEES: "UPDATE_PAYMENTS_COMPETITION_FEES",

  UPDATE_PAYMENTS_OPTIONS_COMPETITION_FEES: 'UPDATE_PAYMENTS_OPTIONS_COMPETITION_FEES',

  //update  default casual fee 
  GET_CASUAL_FEE_DETAIL_API_LOAD: "GET_CASUAL_FEE_DETAIL_API_LOAD",
  GET_CASUAL_FEE_DETAIL_API_SUCCESS: "GET_CASUAL_FEE_DETAIL_API_SUCCESS",

  //update  default seasonal fee 
  GET_SEASONAL_FEE_DETAIL_API_LOAD: "GET_SEASONAL_FEE_DETAIL_API_LOAD",
  GET_SEASONAL_FEE_DETAIL_API_SUCCESS: "GET_SEASONAL_FEE_DETAIL_API_SUCCESS",

  //post api of competition fee payment 
  API_POST_COMPETITION_FEE_PAYMENT_LOAD: "API_POST_COMPETITION_FEE_PAYMENT_LOAD",
  API_POST_COMPETITION_FEE_PAYMENT_SUCCESS: "API_POST_COMPETITION_FEE_PAYMENT_SUCCESS",


  ADD_ANOTHER_DISCOUNT_COMPETITION_FEE: "ADD_ANOTHER_DISCOUNT_COMPETITION_FEE",
  //// Add-Edit competition details
  API_ADD_EDIT_COMPETITION_FEES_DETAILS: "API_ADD_EDIT_COMPETITION_FEES_DETAILS",

  //////Add-Edit competition  section
  API_ADD_EDIT_COMPETITION_FEES_SECTION: "API_ADD_EDIT_COMPETITION_FEES_SECTION",
  CHECK_UNCHECK_COMPETITION_FEES_SECTION: "CHECK_UNCHECK_COMPETITION_FEES_SECTION",

  ////Save competition fee section
  API_SAVE_COMPETITION_FEES_SECTION_LOAD: "API_SAVE_COMPETITION_FEES_SECTION_LOAD",
  API_SAVE_COMPETITION_FEES_SECTION_SUCCESS: "API_SAVE_COMPETITION_FEES_SECTION_SUCCESS",

  // update discount data  in competiton fee
  UPDATE_DISCOUNT_DATA_COMPETITION_FEES: "UPDATE_DISCOUNT_DATA_COMPETITION_FEES",
  // update membership product in competition fee
  UPDATE_DISCOUNT_MEMBERSHIP_PRODUCT: "UPDATE_DISCOUNT_MEMBERSHIP_PRODUCT",
  //  default charity api call
  API_REG_COMPETITION_FEE_DEFAULT_CHARITY_SUCCESS: "API_REG_COMPETITION_FEE_DEFAULT_CHARITY_SUCCESS",
  //on change competion fee discount load
  API_POST_COMPETITION_FEE_DISCOUNT_LOAD: "API_POST_COMPETITION_FEE_DISCOUNT_LOAD",
  API_POST_COMPETITION_FEE_DISCOUNT_SUCCESS: "API_POST_COMPETITION_FEE_DISCOUNT_SUCCESS",


  //default competition  Discount type
  API_COMPETITION_DISCOUNT_TYPE_LOAD: "API_COMPETITION_DISCOUNT_TYPE_LOAD",
  API_COMPETITION_DISCOUNT_TYPE_SUCCESS: "API_COMPETITION_DISCOUNT_TYPE_SUCCESS",

  //clear competition fees  reducer data
  REG_COMPETITION_FEES_CLEARING_REDUCER_DATA: "REG_COMPETITION_FEES_CLEARING_REDUCER_DATA",

  /////get default charity and government voucherss
  API_COMPETITION_FEE_DEFAULT_CHARITY_LOAD: "API_COMPETITION_FEE_DEFAULT_CHARITY_LOAD",
  API_COMPETITION_FEE_DEFAULT_CHARITY_SUCCESS: "API_COMPETITION_FEE_DEFAULT_CHARITY_SUCCESS",



  /////************************Live Score*******************Start

  ////live score player
  API_LIVE_SCORE_PLAYER_LIST_LOAD: "API_LIVE_SCORE_PLAYER_LIST_LOAD",
  API_LIVE_SCORE_PLAYER_LIST_SUCCESS: "API_LIVE_SCORE_PLAYER_LIST_SUCCESS",
  API_LIVE_SCORE_PLAYER_LIST_FAIL: "API_LIVE_SCORE_PLAYER_LIST_FAIL",
  API_LIVE_SCORE_PLAYER_LIST_ERROR: "API_LIVE_SCORE_PLAYER_LIST_ERROR",
  API_LIVE_SCORE_PLAYER_EXPORT_LOAD: "API_LIVE_SCORE_PLAYER_EXPORT_LOAD",
  API_LIVE_SCORE_PLAYER_EXPORT_SUCCESS: "API_LIVE_SCORE_PLAYER_EXPORT_SUCCESS",
  API_LIVE_SCORE_PLAYER_EXPORT_FAIL: "API_LIVE_SCORE_PLAYER_EXPORT_FAIL",
  API_LIVE_SCORE_PLAYER_EXPORT_ERROR: "API_LIVE_SCORE_PLAYER_EXPORT_ERROR",
  ////live score match division
  API_LIVE_SCORE_DIVISION_LOAD: "API_LIVE_SCORE_DIVISION_LOAD",
  API_LIVE_SCORE_DIVISION_SUCCESS: "API_LIVE_SCORE_DIVISION_SUCCESS",
  API_LIVE_SCORE_DIVISION_FAIL: "API_LIVE_SCORE_DIVISION_FAIL",
  API_LIVE_SCORE_DIVISION_ERROR: "API_LIVE_SCORE_DIVISION_ERROR",
  API_LIVE_SCORE_LADDERS_DIVISION_LOAD: "API_LIVE_SCORE_LADDERS_DIVISION_LOAD",
  API_LIVE_SCORE_LADDERS_DIVISION_SUCCESS: "API_LIVE_SCORE_LADDERS_DIVISION_SUCCESS",
  API_LIVE_SCORE_LADDERS_DIVISION_FAIL: "API_LIVE_SCORE_LADDERS_DIVISION_FAIL",
  API_LIVE_SCORE_LADDERS_DIVISION_ERROR: "API_LIVE_SCORE_LADDERS_DIVISION_ERROR",
  API_LIVE_SCORE_LADDERS_LIST_LOAD: "API_LIVE_SCORE_LADDERS_LIST_LOAD",
  API_LIVE_SCORE_LADDERS_LIST_SUCCESS: "API_LIVE_SCORE_LADDERS_LIST_SUCCESS",
  API_LIVE_SCORE_LADDERS_LIST_FAIL: "API_LIVE_SCORE_LADDERS_LIST_FAIL",
  API_LIVE_SCORE_LADDERS_LIST_ERROR: "API_LIVE_SCORE_LADDERS_LIST_ERROR",
  API_LIVE_SCORE_MATCH_LIST_LOAD: "API_LIVE_SCORE_MATCH_LIST_LOAD",
  API_LIVE_SCORE_MATCH_LIST_SUCCESS: "API_LIVE_SCORE_MATCH_LIST_SUCCESS",
  API_LIVE_SCORE_MATCH_LIST_FAIL: "API_LIVE_SCORE_MATCH_LIST_FAIL",
  API_LIVE_SCORE_MATCH_LIST_ERROR: "API_LIVE_SCORE_MATCH_LIST_ERROR",
  API_LIVE_SCORE_TEAM_LOAD: "API_LIVE_SCORE_TEAM_LOAD",
  API_LIVE_SCORE_TEAM_SUCCESS: "API_LIVE_SCORE_TEAM_SUCCESS",
  API_LIVE_SCORE_TEAM_FAIL: "API_LIVE_SCORE_TEAM_FAIL",
  API_LIVE_SCORE_TEAM_ERROR: "API_LIVE_SCORE_TEAM_ERROR",
  API_LIVE_SCORE_INCIDENT_LIST_LOAD: "API_LIVE_SCORE_INCIDENT_LIST_LOAD",
  API_LIVE_SCORE_INCIDENT_LIST_SUCCESS: "API_LIVE_SCORE_INCIDENT_LIST_SUCCESS",
  API_LIVE_SCORE_INCIDENT_LIST_FAIL: "API_LIVE_SCORE_INCIDENT_LIST_FAIL",
  API_LIVE_SCORE_INCIDENT_LIST_ERROR: "API_LIVE_SCORE_INCIDENT_LIST_ERROR",
  API_LIVE_SCORE_ADD_EDIT_MATCH_LOAD: "API_LIVE_SCORE_ADD_EDIT_MATCH_LOAD",
  API_LIVE_SCORE_ADD_EDIT_MATCH_SUCCESS: "API_LIVE_SCORE_ADD_EDIT_MATCH_SUCCESS",
  API_LIVE_SCORE_ADD_EDIT_MATCH_FAIL: "API_LIVE_SCORE_ADD_EDIT_MATCH_FAIL",
  API_LIVE_SCORE_ADD_EDIT_MATCH_ERROR: "API_LIVE_SCORE_ADD_EDIT_MATCH_ERROR",
  API_LIVE_SCORE_ADD_MATCH: "API_LIVE_SCORE_ADD_MATCH",
  API_LIVE_SCORE_UPDATE_MATCH: 'API_LIVE_SCORE_UPDATE_MATCH',
  ////create match
  API_LIVE_SCORE_CREATE_MATCH_LOAD: "API_LIVE_SCORE_CREATE_MATCH_LOAD",
  API_LIVE_SCORE_CREATE_MATCH_SUCCESS: "API_LIVE_SCORE_CREATE_MATCH_SUCCESS",
  API_LIVE_SCORE_CREATE_MATCH_FAIL: "API_LIVE_SCORE_CREATE_MATCH_FAIL",
  API_LIVE_SCORE_CREATE_MATCH_ERROR: "API_LIVE_SCORE_CREATE_MATCH_ERROR",
  ////news list
  API_LIVE_SCORE_NEWS_LIST_LOAD: "API_LIVE_SCORE_NEWS_LIST_LOAD",
  API_LIVE_SCORE_NEWS_LIST_SUCCESS: "API_LIVE_SCORE_NEWS_LIST_SUCCESS",
  API_LIVE_SCORE_NEWS_LIST_FAIL: "API_LIVE_SCORE_NEWS_LIST_FAIL",
  API_LIVE_SCORE_NEWS_LIST_ERROR: "API_LIVE_SCORE_NEWS_LIST_ERROR",
  ////Banners
  API_LIVE_SCORE_BANNERS_LOAD: "API_LIVE_SCORE_BANNERS_LOAD",
  API_LIVE_SCORE_BANNERS_SUCCESS: "API_LIVE_SCORE_BANNERS_SUCCESS",
  API_LIVE_SCORE_BANNERS_FAIL: "API_LIVE_SCORE_BANNERS_FAIL",
  API_LIVE_SCORE_BANNERS_ERROR: "API_LIVE_SCORE_BANNERS_ERROR",
  ////Create Round
  API_LIVE_SCORE_CREATE_ROUND_LOAD: "API_LIVE_SCORE_CREATE_ROUND_LOAD",
  API_LIVE_SCORE_CREATE_ROUND_SUCCESS: "API_LIVE_SCORE_CREATE_ROUND_SUCCESS",
  API_LIVE_SCORE_CREATE_ROUND_FAIL: "API_LIVE_SCORE_CREATE_ROUND_FAIL",
  API_LIVE_SCORE_CREATE_ROUND_ERROR: "API_LIVE_SCORE_CREATE_ROUND_ERROR",

  API_LIVE_SCORE_ADD_NEWS_DETAILS: "API_LIVE_SCORE_ADD_NEWS_DETAILS",
  API_LIVE_SCORE_UPDATE_NEWS: 'API_LIVE_SCORE_UPDATE_NEWS',
  ////Add News
  API_LIVE_SCORE_ADD_NEWS_LOAD: "API_LIVE_SCORE_ADD_NEWS_LOAD",
  API_LIVE_SCORE_ADD_NEWS_SUCCESS: "API_LIVE_SCORE_ADD_NEWS_SUCCESS",
  API_LIVE_SCORE_ADD_NEWS_FAIL: "API_LIVE_SCORE_ADD_NEWS_FAIL",
  API_LIVE_SCORE_ADD_NEWS_ERROR: "API_LIVE_SCORE_ADD_NEWS_ERROR",
  API_LIVE_SCORE_REFRESH_NEWS: 'API_LIVE_SCORE_REFRESH_NEWS',
  ////Manager list
  API_LIVE_SCORE_MANAGER_LIST_LOAD: "API_LIVE_SCORE_MANAGER_LIST_LOAD",
  API_LIVE_SCORE_MANAGER_LIST_SUCCESS: "API_LIVE_SCORE_MANAGER_LIST_SUCCESS",
  API_LIVE_SCORE_MANAGER_LIST_FAIL: "API_LIVE_SCORE_MANAGER_LIST_FAIL",
  API_LIVE_SCORE_MANAGER_LIST_ERROR: "API_LIVE_SCORE_MANAGER_LIST_ERROR",
  //// Scorer List
  API_LIVE_SCORE_SCORER_LIST_LOAD: "API_LIVE_SCORE_SCORER_LIST_LOAD",
  API_LIVE_SCORE_SCORER_LIST_SUCCESS: "API_LIVE_SCORE_SCORER_LIST_SUCCESS",
  API_LIVE_SCORE_SCORER_LIST_FAIL: "API_LIVE_SCORE_SCORER_LIST_FAIL",
  API_LIVE_SCORE_SCORER_LIST_ERROR: "API_LIVE_SCORE_SCORER_LIST_ERROR",
  ////Bulk Match Push Back
  API_LIVE_SCORE_BULK_PUSH_BACK_LOAD: "API_LIVE_SCORE_BULK_PUSH_BACK_LOAD",
  API_LIVE_SCORE_BULK_PUSH_BACK_SUCCESS: "API_LIVE_SCORE_BULK_PUSH_BACK_SUCCESS",
  API_LIVE_SCORE_BULK_PUSH_BACK_FAIL: "API_LIVE_SCORE_BULK_PUSH_BACK_FAIL",
  API_LIVE_SCORE_BULK_PUSH_BACK_ERROR: "API_LIVE_SCORE_BULK_PUSH_BACK_ERROR",
  ////Bulk Match Bring Forward
  API_LIVE_SCORE_BULK_PUSH_BACK_LOAD: "API_LIVE_SCORE_BULK_PUSH_BACK_LOAD",
  API_LIVE_SCORE_BULK_PUSH_BACK_SUCCESS: "API_LIVE_SCORE_BULK_PUSH_BACK_SUCCESS",
  API_LIVE_SCORE_BULK_PUSH_BACK_FAIL: "API_LIVE_SCORE_BULK_PUSH_BACK_FAIL",
  API_LIVE_SCORE_BULK_PUSH_BACK_ERROR: "API_LIVE_SCORE_BULK_PUSH_BACK_ERROR",
  ////Bulk Match Push Back
  API_LIVE_SCORE_BULK_BRING_FORWARD_LOAD: "API_LIVE_SCORE_BULK_BRING_FORWARD_LOAD",
  API_LIVE_SCORE_BULK_BRING_FORWARD_SUCCESS: "API_LIVE_SCORE_BULK_BRING_FORWARD_SUCCESS",
  API_LIVE_SCORE_BULK_BRING_FORWARD_FAIL: "API_LIVE_SCORE_BULK_BRING_FORWARD_FAIL",
  API_LIVE_SCORE_BULK_BRING_FORWARD_ERROR: "API_LIVE_SCORE_BULK_BRING_FORWARD_ERROR",
  ////Bulk End Matches
  API_LIVE_SCORE_BULK_END_MATCHES_LOAD: "API_LIVE_SCORE_BULK_END_MATCHES_LOAD",
  API_LIVE_SCORE_BULK_END_MATCHES_SUCCESS: "API_LIVE_SCORE_BULK_END_MATCHES_SUCCESS",
  API_LIVE_SCORE_BULK_END_MATCHES_FAIL: "API_LIVE_SCORE_BULK_END_MATCHES_FAIL",
  API_LIVE_SCORE_BULK_END_MATCHES_ERROR: "API_LIVE_SCORE_BULK_END_MATCHES_ERROR",
  API_LIVE_SCORE_BULK_MATCH: 'API_LIVE_SCORE_BULK_MATCH',
  API_LIVE_SCORE_UPDATE_BULK: 'API_LIVE_SCORE_UPDATE_BULK',
  ////Remove Banner
  API_LIVE_SCORE_REMOVE_BANNER_LOAD: "API_LIVESCORE_ADD_REMOVE_BANNER_LOAD",
  API_LIVE_SCORE_REMOVE_BANNER_SUCCESS: "API_LIVESCORE_ADD_REMOVE_BANNER_SUCCESS",
  API_LIVE_SCORE_REMOVE_BANNER_FAIL: "API_LIVESCORE_ADD_REMOVE_BANNER_FAIL",
  API_LIVE_SCORE_REMOVE_BANNER_ERROR: "API_LIVESCORE_ADD_REMOVE_BANNER_ERROR",
  ////Add Banner
  API_LIVE_SCORE_ADD_BANNER_LOAD: "API_LIVESCORE_ADD_BANNER_LOAD",
  API_LIVE_SCORE_ADD_BANNER_SUCCESS: "API_LIVESCORE_ADD_BANNER_SUCCESS",
  API_LIVE_SCORE_ADD_BANNER_FAIL: "API_LIVESCORE_ADD_BANNER_FAIL",
  API_LIVE_SCORE_ADD_BANNER_ERROR: "API_LIVESCORE_ADD_BANNER_ERROR",
  //// Bulk Doble Header
  API_LIVE_SCORE_BULK_DOUBLE_HEADER_LOAD: "API_LIVE_SCORE_BULK_DOUBLE_HEADER_LOAD",
  API_LIVE_SCORE_BULK_DOUBLE_HEADER_SUCCESS: "API_LIVE_SCORE_BULK_DOUBLE_HEADER_SUCCESS",
  API_LIVE_SCORE_BULK_DOUBLE_HEADER_FAIL: "API_LIVE_SCORE_BULK_DOUBLE_HEADER_FAIL",
  API_LIVE_SCORE_BULK_DOUBLE_HEADER_ERROR: "API_LIVE_SCORE_BULK_DOUBLE_HEADER_ERROR",
  ////Api Abandon Matches
  API_LIVE_SCORE_BULK_ABANDON_MATCHES_LOAD: "API_LIVE_SCORE_BULK_ABANDON_MATCHES_LOAD",
  API_LIVE_SCORE_BULK_ABANDON_MATCHES_SUCCESS: "API_LIVE_SCORE_BULK_ABANDON_MATCHES_SUCCESS",
  API_LIVE_SCORE_BULK_ABANDON_MATCHES_FAIL: "API_LIVE_SCORE_BULK_ABANDON_MATCHES_FAIL",
  API_LIVE_SCORE_BULK_ABANDON_MATCHES_ERROR: "API_LIVE_SCORE_BULK_ABANDON_MATCHES_ERROR",

  ////************************Live Score*******************End

  ////Competition Dashboard
  API_COMPETITION_DASHBOARD_LOAD: 'API_COMPETITION_DASHBOARD_LOAD',
  API_COMPETITION_DASHBOARD_SUCCESS: "API_COMPETITION_DASHBOARD_SUCCESS",
  API_COMPETITION_DASHBOARD_FAIL: "API_COMPETITION_DASHBOARD_FAIL",
  API_COMPETITION_DASHBOARD_ERROR: "API_COMPETITION_DASHBOARD_ERROR",

  ////Get Year
  API_GET_YEAR_LOAD: 'API_GET_YEAR_LOAD',
  API_GET_YEAR_SUCCESS: "API_GET_YEAR_SUCCESS",
  API_GET_YEAR_FAIL: "API_GET_YEAR_FAIL",
  API_GET_YEAR_ERROR: "API_GET_YEAR_ERROR",


  /////////get the default competition logo api
  API_COMPETITION_FEE_DEFAULT_LOGO_LOAD: "API_COMPETITION_FEE_DEFAULT_LOGO_LOAD",
  API_COMPETITION_FEE_DEFAULT_LOGO_SUCCESS: "API_COMPETITION_FEE_DEFAULT_LOGO_SUCCESS",

  /////time slots

  API_GET_COMPETITION_WITH_TIME_SLOTS_LOAD: "API_GET_COMPETITION_WITH_TIME_SLOTS_LOAD",
  API_GET_COMPETITION_WITH_TIME_SLOTS_SUCCESS: "API_GET_COMPETITION_WITH_TIME_SLOTS_SUCCESS",

  //competition fail and eror
  API_COMPETITION_ERROR: "API_COMPETITION_ERROR",
  API_COMPETITION_FAIL: "API_COMPETITION_FAIL",



  API_GET_YEAR_COMPETITION_LOAD: 'API_GET_YEAR_COMPETITION_LOAD',
  API_GET_YEAR_COMPETITION_SUCCESS: "API_GET_YEAR_COMPETITION_SUCCESS",
  API_GET_YEAR_COMPETITION_FAIL: "API_GET_YEAR_COMPETITION_FAIL",
  API_GET_YEAR_COMPETITION_ERROR: "API_GET_YEAR_COMPETITION_ERROR",


  /* *********** Competition Management Starts ****************** */

  // Competition Format Get
  API_GET_COMPETITION_FORMAT_SUCCESS: "API_GET_COMPETITION_FORMAT_SUCCESS",
  API_GET_COMPETITION_FORMAT_LOAD: "API_GET_COMPETITION_FORMAT_LOAD",

  // Competition Format Save
  API_SAVE_COMPETITION_FORMAT_SUCCESS: "API_SAVE_COMPETITION_FORMAT_SUCCESS",
  API_SAVE_COMPETITION_FORMAT_LOAD: "API_SAVE_COMPETITION_FORMAT_LOAD",

  API_COMPETITION_FORMAT_FAIL: "API_COMPETITION_FORMAT_FAIL",
  API_COMPETITION_FORMAT_ERROR: "API_COMPETITION_FORMAT_ERROR",

  // Competition Finals Get
  API_GET_COMPETITION_FINALS_SUCCESS: "API_GET_COMPETITION_FINALS_SUCCESS",
  API_GET_COMPETITION_FINALS_LOAD: "API_GET_COMPETITION_FINALS_LOAD",

  // Competition Finals Save
  API_SAVE_COMPETITION_FINALS_SUCCESS: "API_SAVE_COMPETITION_FINALS_SUCCESS",
  API_SAVE_COMPETITION_FINALS_LOAD: "API_SAVE_COMPETITION_FINALS_LOAD",

  API_COMPETITION_FINALS_FAIL: "API_COMPETITION_FINALS_FAIL",
  API_COMPETITION_FINALS_ERROR: "API_COMPETITION_FINALS_ERROR",

  // Ladder Format Get
  API_GET_LADDER_FORMAT_SUCCESS: "API_GET_LADDER_FORMAT_SUCCESS",
  API_GET_LADDER_FORMAT_LOAD: "API_GET_LADDER_FORMAT_LOAD",

  // Ladder Format Save
  API_SAVE_LADDER_FORMAT_SUCCESS: "API_SAVE_LADDER_FORMAT_SUCCESS",
  API_SAVE_LADDER_FORMAT_LOAD: "API_SAVE_LADDER_FORMAT_LOAD",

  API_LADDER_FORMAT_FAIL: "API_LADDER_FORMAT_FAIL",
  API_LADDER_FORMAT_ERROR: "API_LADDER_FORMAT_ERROR",

  //Match Types
  API_MATCH_TYPES_LOAD: "API_MATCH_TYPES_LOAD",
  API_MATCH_TYPES_SUCCESS: "API_MATCH_TYPES_SUCCESS",

  //Update Competition Format
  UPDATE_COMPETITION_FORMAT: "UPDATE_COMPETITION_FORMAT",

  //Update Competition Finals
  UPDATE_COMPETITION_FINALS: "UPDATE_COMPETITION_FINALS",

  //Update Ladder Format
  UPDATE_LADDER_FORMAT: "UPDATE_LADDER_FORMAT",

  //Competition Types Reference
  API_COMPETITION_TYPES_LOAD: "API_COMPETITION_TYPES_LOAD",
  API_COMPETITION_TYPES_SUCCESS: "API_COMPETITION_TYPES_SUCCESS",

  //Competition Formats
  API_COMPETITION_FORMAT_TYPES_LOAD: "API_COMPETITION_FORMAT_TYPES_LOAD",
  API_COMPETITION_FORMAT_TYPES_SUCCESS: "API_COMPETITION_FORMAT_TYPES_SUCCESS",

  /* ********** Competition Management Ends ***************** */


  //competition time and slot fail and eror
  API_COMPETITION_TIMESLOT_ERROR: "API_COMPETITION_TIMESLOT_ERROR",
  API_COMPETITION_TIMESLOT_FAIL: "API_COMPETITION_TIMESLOT_FAIL",

  //update competition time and slots
  UPDATE_POST_DATA_TIME_SLOTS_COMPETITION: "UPDATE_POST_DATA_TIME_SLOTS_COMPETITION",
  updateTimeSlotData: "updateTimeSlotData",
  API_TIME_SLOT_INIT_LOAD: "API_TIME_SLOT_INIT_LOAD",
  API_TIME_SLOT_INIT_SUCCESS: "API_TIME_SLOT_INIT_SUCCESS",
  API_COMMON_SAGA_ERROR: "API_COMMON_SAGA_ERROR",
  API_COMMON_SAGA_FAIL: "API_COMMON_SAGA_FAIL",

  ////Common Refrence Constant
  API_GET_COMMON_REF_DATA_LOAD: 'API_GET_COMMON_REF_DATA_LOAD',
  API_GET_COMMON_REF_DATA_SUCCESS: "API_GET_COMMON_REF_DATA_SUCCESS",

  API_ADD_VENUE_LOAD: "API_ADD_VENUE_LOAD",
  API_ADD_VENUE_SUCCESS: "API_ADD_VENUE_SUCCESS",

  ////VENUE CONSTRAINTS List
  API_VENUE_CONSTRAINTS_LIST_LOAD: 'API_VENUE_CONSTRAINTS_LIST_LOAD',
  API_VENUE_CONSTRAINTS_LIST_SUCCESS: "API_VENUE_CONSTRAINTS_LIST_SUCCESS",
  API_VENUE_CONSTRAINTS_LIST_FAIL: "API_VENUE_CONSTRAINTS_LIST_FAIL",
  API_VENUE_CONSTRAINTS_LIST_ERROR: "API_VENUE_CONSTRAINTS_LIST_ERROR",

  API_REFRESH_VENUE_FIELDS: "API_REFRESH_VENUE_FIELDS",
  API_UPDATE_COMPETITION_LIST: "API_UPDATE_COMPETITION_LIST",
  API_UPDATE_VENUE_TIME_DATA: "API_UPDATE_VENUE_TIME_DATA",

  API_UPDATE_VENUE_CONSTRAINTS_DATA: "API_UPDATE_VENUE_CONSTRAINTS_DATA",

  ////Venue List for own competitionvenue and times
  API_VENUE_LIST_LOAD: 'API_VENUE_LIST_LOAD',
  API_VENUE_LIST_SUCCESS: "API_VENUE_LIST_SUCCESS",

  //competition part player grading fail and eror
  API_COMPETITION_PART_PLAYER_GRADING_FAIL: "API_COMPETITION_PART_PLAYER_GRADING_FAIL",
  API_COMPETITION_PART_PLAYER_GRADING_ERROR: "API_COMPETITION_PART_PLAYER_GRADING_ERROR",


  //competition part player grade calculate player grading summmary get API
  API_GET_COMPETITION_PART_PLAYER_GRADE_CALCULATE_SUMMMARY_LIST_LOAD: "API_GET_COMPETITION_PART_PLAYER_GRADE_CALCULATE_SUMMMARY_LIST_LOAD",
  API_GET_COMPETITION_PART_PLAYER_GRADE_CALCULATE_SUMMMARY_LIST_SUCCESS: "API_GET_COMPETITION_PART_PLAYER_GRADE_CALCULATE_SUMMMARY_LIST_SUCCESS",

  /////////////competition part player grade calculate player grading summmary data on Change table input
  ONCHANGE_COMPETITION_PART_PLAYER_GRADE_CALCULATE_SUMMMARY_DATA: "ONCHANGE_COMPETITION_PART_PLAYER_GRADE_CALCULATE_SUMMMARY_DATA",

  //competition own proposed team grading  fail and eror
  API_COMPETITION_OWN_TEAM_GRADING_FAIL: "API_COMPETITION_OWN_TEAM_GRADING_FAIL",
  API_COMPETITION_OWN_TEAM_GRADING_ERROR: "API_COMPETITION_OWN_TEAM_GRADING_ERROR",


  //competition own proposed team grading get api
  API_GET_COMPETITION_OWN_PROPOSED_TEAM_GRADING_LIST_LOAD: "API_GET_COMPETITION_OWN_PROPOSED_TEAM_GRADING_LIST_LOAD",
  API_GET_COMPETITION_OWN_PROPOSED_TEAM_GRADING_LIST_SUCCESS: "API_GET_COMPETITION_OWN_PROPOSED_TEAM_GRADING_LIST_SUCCESS",

  /////////////competition own proposed team grading data on Change table input
  ONCHANGE_COMPETITION_OWN_PROPOSED_TEAM_GRADING_DATA: "ONCHANGE_COMPETITION_OWN_PROPOSED_TEAM_GRADING_DATA",

  /* Affilaites Starts here  */

  API_USER_FAIL: "API_USER_FAIL",
  API_USER_ERROR: "API_USER_ERROR",

  /*  Affiliates Ends here  */

  ///get the divisions list on the basis of year and competition
  API_GET_DIVISIONS_LIST_ON_YEAR_AND_COMPETITION_LOAD: "API_GET_DIVISIONS_LIST_ON_YEAR_AND_COMPETITION_LOAD",
  API_GET_DIVISIONS_LIST_ON_YEAR_AND_COMPETITION_SUCCESS: "API_GET_DIVISIONS_LIST_ON_YEAR_AND_COMPETITION_SUCCESS",

  ///get the grades reference data
  API_GRADES_REFERENCE_LIST_LOAD: 'API_GRADES_REFERENCE_LIST_LOAD',
  API_GRADES_REFERENCE_LIST_SUCCESS: "API_GRADES_REFERENCE_LIST_SUCCESS",

  //competition own final team grading save  api
  API_SAVE_COMPETITION_OWN_FINAL_TEAM_GRADING_LOAD: "API_SAVE_COMPETITION_OWN_FINAL_TEAM_GRADING_LOAD",
  API_SAVE_COMPETITION_OWN_FINAL_TEAM_GRADING_SUCCESS: "API_SAVE_COMPETITION_OWN_FINAL_TEAM_GRADING_SUCCESS",

  //clear own  competition  team grading reducer data
  OWN_COMP_TEAM_GRADING_CLEARING_PARTICULAR_REDUCER_DATA: "OWN_COMP_TEAM_GRADING_CLEARING_PARTICULAR_REDUCER_DATA",

  //////competition part  proposed team grading get api
  API_GET_COMPETITION_PART_PROPOSED_TEAM_GRADING_LIST_LOAD: "API_GET_COMPETITION_PART_PROPOSED_TEAM_GRADING_LIST_LOAD",
  API_GET_COMPETITION_PART_PROPOSED_TEAM_GRADING_LIST_SUCCESS: "API_GET_COMPETITION_PART_PROPOSED_TEAM_GRADING_LIST_SUCCESS",


  /////////////competition part  proposed team grading data on Change table input
  ONCHANGE_COMPETITION_PART_PROPOSED_TEAM_GRADING_DATA: "ONCHANGE_COMPETITION_PART_PROPOSED_TEAM_GRADING_DATA",

  //competition part proposed team grading save  api
  API_SAVE_COMPETITION_PART_PROPOSED_TEAM_GRADING_LOAD: "API_SAVE_COMPETITION_PART_PROPOSED_TEAM_GRADING_LOAD",
  API_SAVE_COMPETITION_PART_PROPOSED_TEAM_GRADING_SUCCESS: "API_SAVE_COMPETITION_PART_PROPOSED_TEAM_GRADING_SUCCESS",

  //add remove time slot 
  UPDATE_POST_DATA_TIME_SLOTS_MANUAL_COMPETITION: "UPDATE_POST_DATA_TIME_SLOTS_MANUAL_COMPETITION",
  Api_ADD_REMOVE_TIME_SLOT_TABLE: "Api_ADD_REMOVE_TIME_SLOT_TABLE",


  //post api time slot for save time slots
  API_COMPETITION_TIMESLOT_POST_LOAD: "API_COMPETITION_TIMESLOT_POST_LOAD",
  API_COMPETITION_TIMESLOT_POST_SUCCESS: "API_COMPETITION_TIMESLOT_POST_SUCCESS",

  ////save the competition part player grade calculate player grading summmary or say proposed player grading toggle
  API_SAVE_COMPETITION_PART_PLAYER_GRADE_CALCULATE_SUMMMARY_LIST_LOAD: "API_SAVE_COMPETITION_PART_PLAYER_GRADE_CALCULATE_SUMMMARY_LIST_LOAD",
  API_SAVE_COMPETITION_PART_PLAYER_GRADE_CALCULATE_SUMMMARY_LIST_SUCCESS: "API_SAVE_COMPETITION_PART_PLAYER_GRADE_CALCULATE_SUMMMARY_LIST_SUCCESS",


  //////////get the own team grading summary listing data
  API_GET_COMPETITION_OWN_TEAM_GRADING_SUMMARY_LIST_LOAD: "API_GET_COMPETITION_OWN_TEAM_GRADING_SUMMARY_LIST_LOAD",
  API_GET_COMPETITION_OWN_TEAM_GRADING_SUMMARY_LIST_SUCCESS: "API_GET_COMPETITION_OWN_TEAM_GRADING_SUMMARY_LIST_SUCCESS",

  //competition part player grading get API 
  API_GET_COMPETITION_PART_PLAYER_GRADING_LIST_LOAD: "API_GET_COMPETITION_PART_PLAYER_GRADING_LIST_LOAD",
  API_GET_COMPETITION_PART_PLAYER_GRADING_LIST_SUCCESS: "API_GET_COMPETITION_PART_PLAYER_GRADING_LIST_SUCCESS",


  //clear particular reducer data of competition part player grading 
  CLEARING_COMPETITION_PART_PLAYER_GRADING_REDUCER_DATA: "CLEARING_COMPETITION_PART_PLAYER_GRADING_REDUCER_DATA",

  // Competition Draws
  API_GET_COMPETITION_DRAWS_SUCCESS: "API_GET_COMPETITION_DRAWS_SUCCESS",
  API_GET_COMPETITION_DRAWS_LOAD: "API_GET_COMPETITION_DRAWS_LOAD",

  API_COMPETITION_DRAWS_FAIL: "API_COMPETITION_DRAWS_FAIL",
  API_COMPETITION_DRAWS_ERROR: "API_COMPETITION_DRAWS_ERROR",

  // Competition draws rounds 
  API_GET_COMPETITION_DRAWS_ROUNDS_LOAD: "API_GET_COMPETITION_DRAWS_ROUNDS_LOAD",
  API_GET_COMPETITION_DRAWS_ROUNDS_SUCCESS: "API_GET_COMPETITION_DRAWS_ROUNDS_SUCCESS",


  API_VENUE_CONSTRAINT_POST_LOAD: "API_VENUE_CONSTRAINT_POST_LOAD",
  API_VENUE_CONSTRAINT_POST_SUCCESS: "API_VENUE_CONSTRAINT_POST_SUCCESS",
  API_VENUE_CONSTRAINT_POST_FAIL: "API_VENUE_CONSTRAINT_POST_FAIL",
  API_VENUE_CONSTRAINT_POST_ERROR: "API_VENUE_CONSTRAINT_POST_ERROR",

  ////clear venue and time data after competition change
  CLEAR_VENUE_TIMES_DATA: "CLEAR_VENUE_TIMES_DATA",

  ////delete prefence object
  DELETE_PREFENCE_OBJECT: "DELETE_PREFENCE_OBJECT",

  /////////save the changed grade name in own competition team grading summary data
  API_SAVE_UPDATED_GRADE_NAME_TEAM_GRADING_SUMMARY_LOAD: "API_SAVE_UPDATED_GRADE_NAME_TEAM_GRADING_SUMMARY_LOAD",
  API_SAVE_UPDATED_GRADE_NAME_TEAM_GRADING_SUMMARY_SUCCESS: "API_SAVE_UPDATED_GRADE_NAME_TEAM_GRADING_SUMMARY_SUCCESS",

  ////////////team grading summmary publish
  API_PUBLISH_TEAM_GRADING_SUMMARY_LOAD: "API_PUBLISH_TEAM_GRADING_SUMMARY_LOAD",
  API_PUBLISH_TEAM_GRADING_SUMMARY_SUCCESS: "API_PUBLISH_TEAM_GRADING_SUMMARY_SUCCESS",


  /////////////competition team grading summmary onchange table data
  ONCHANGE_COMPETITION_TEAM_GRADING_SUMMARY_DATA: "ONCHANGE_COMPETITION_TEAM_GRADING_SUMMARY_DATA",


  //// Update draws
  API_UPDATE_COMPETITION_DRAWS_LOAD: "API_UPDATE_COMPETITION_DRAWS_LOAD",
  API_UPDATE_COMPETITION_DRAWS_SUCCESS: "API_UPDATE_COMPETITION_DRAWS_SUCCESS",

  //// Save Draws
  API_UPDATE_COMPETITION_SAVE_DRAWS_LOAD: "API_UPDATE_COMPETITION__SAVE_DRAWS_LOAD",
  API_UPDATE_COMPETITION_SAVE_DRAWS_SUCCESS: "API_UPDATE_COMPETITION__SAVE_DRAWS_SUCCESS",

  ///clear competion data
  CLEAR_COMPETITION_DATA: "CLEAR_COMPETITION_DATA",

  ////Api Add/Edit Player
  API_LIVE_SCORE_ADD_EDIT_PLAYER_LOAD: "API_LIVE_SCORE_ADD_EDIT_PLAYER_LOAD",
  API_LIVE_SCORE_ADD_EDIT_PLAYER_SUCCESS: "API_LIVE_SCORE_ADD_EDIT_PLAYER_SUCCESS",

  ////Update Player Data
  API_LIVE_SCORE_UPDATE_PLAYER: "API_LIVE_SCORE_UPDATE_PLAYER",

  API_LIVE_SCORE_FAIL: "API_LIVE_SCORE_FAIL",
  API_LIVE_SCORE_ERROR: "API_LIVE_SCORE_ERROR",

  ///Add/Edit Manager
  API_LIVE_SCORE_ADD_EDIT_MANAGER_LOAD: "API_LIVE_SCORE_ADD_EDIT_MANAGER_LOAD",
  API_LIVE_SCORE_ADD_EDIT_MANAGER_SUCCESS: "API_LIVE_SCORE_ADD_EDIT_MANAGER_SUCCESS",


  ////Dashboard
  API_LIVE_SCORE_DASHBOARD_LOAD: "API_LIVE_SCORE_DASHBOARD_LOAD",
  API_LIVE_SCORE_DASHBOARD_SUCCESS: "API_LIVE_SCORE_DASHBOARD_SUCCESS",

  //liveScore addBanner update	
  API_LIVE_SCORE_ADD_BANNER_UPDATE: "API_LIVE_SCORE_ADD_BANNER_UPDATE",

  //liveScore clear banner reducer	
  API_LIVE_SCORE_CLEAR_BANNER_REDUCER: "API_LIVE_SCORE_CLEAR_BANNER_REDUCER",
  //// Get Competition Venue

  API_GET_COMPETITION_VENUES_LOAD: "API_GET_COMPETITION_VENUES_LOAD",
  API_GET_COMPETITION_VENUES_SUCCESS: "API_GET_COMPETITION_VENUES_SUCCESS",

  //// Added 2 March***Start

  ////News saga fail and error
  API_NEWS_SAGA_FAIL: "API_NEWS_SAGA_FAIL",
  API_NEWS_SAGA_ERROR: "API_NEWS_SAGA_ERROR",

  API_LIVE_SCORE_MANAGER_FAIL: "API_LIVE_SCORE_MANAGER_FAIL",
  API_LIVE_SCORE_MANAGER_ERROR: "API_LIVE_SCORE_MANAGER_ERROR",

  API_LIVE_SCORE_UPDATE_MANAGER_DATA: "API_LIVE_SCORE_UPDATE_MANAGER_DATA",

  API_LIVE_SCORE_BULK_MATCH_FAIL: "API_LIVE_SCORE_BULK_MATCH_FAIL",
  API_LIVE_SCORE_BULK_MATCH_ERROR: "API_LIVE_SCORE_BULK_MATCH_ERROR",

  API_LIVE_SCORE_DASHBOARD_FAIL: "API_LIVE_SCORE_DASHBOARD_FAIL",
  API_LIVE_SCORE_DASHBOARD_ERROR: "API_LIVE_SCORE_DASHBOARD_ERROR",

  API_LIVE_SCORE_GOAL_FAIL: "API_LIVE_SCORE_GOAL_FAIL",
  API_LIVE_SCORE_GOAL_ERROR: "API_LIVE_SCORE_GOAL_ERROR",

  //// Added 2 March***End

  //  delete add venue GameDays object
  DELETE_PREFENCE_OBJECT_ADD_VENUE: "DELETE_PREFENCE_OBJECT_ADD_VENUE",

  API_LIVE_SCORE_PLAYER_FAIL: "API_LIVE_SCORE_PLAYER_FAIL",
  API_LIVE_SCORE_PLAYER_ERROR: "API_LIVE_SCORE_PLAYER_ERROR",

  ///////////get the competition final grades on the basis of competition and division
  API_GET_COMPETITION_FINAL_GRADES_LIST_LOAD: "API_GET_COMPETITION_FINAL_GRADES_LIST_LOAD",
  API_GET_COMPETITION_FINAL_GRADES_LIST_SUCCESS: "API_GET_COMPETITION_FINAL_GRADES_LIST_SUCCESS",

  //////update draws court timing where N/A(null) is there
  API_UPDATE_COMPETITION_DRAWS_COURT_TIMINGS_LOAD: "API_UPDATE_COMPETITION_DRAWS_COURT_TIMINGS_LOAD",
  API_UPDATE_COMPETITION_DRAWS_COURT_TIMINGS_SUCCESS: "API_UPDATE_COMPETITION_DRAWS_COURT_TIMINGS_SUCCESS",
  //clear match data
  API_LIVE_SCORE_CLEAR_MATCH_DATA: "API_LIVE_SCORE_CLEAR_MATCH_DATA",

  API_LIVE_SCORE_DELETE_MATCH_LOAD: "API_LIVE_SCORE_DELETE_MATCH_LOAD",
  API_LIVE_SCORE_DELETE_MATCH_SUCCESS: "API_LIVE_SCORE_DELETE_MATCH_SUCCESS",

  //// 6 March
  API_GET_TEAM_VIEW_PLAYER_LIST_LOAD: "API_GET_TEAM_VIEW_PLAYER_LIST_LOAD",
  API_GET_TEAM_VIEW_PLAYER_LIST_SUCCESS: "API_GET_TEAM_VIEW_PLAYER_LIST_SUCCESS",

  API_LIVE_SCORE_DELETE_TEAM_LOAD: "API_LIVE_SCORE_DELETE_TEAM_LOAD",
  API_LIVE_SCORE_DELETE_TEAM_SUCCESS: "API_LIVE_SCORE_DELETE_TEAM_SUCCESS",

  ///Favourite Team Reference List
  API_FAVOURITE_TEAM_REFERENCE_LOAD: 'API_FAVOURITE_TEAM_REFERENCE_LOAD',
  API_FAVOURITE_TEAM_REFERENCE_SUCCESS: "API_FAVOURITE_TEAM_REFERENCE_SUCCESS",

  /// Firebird Player Reference  List
  API_FIREBIRD_PLAYER_REFERENCE_LOAD: 'API_FIREBIRD_PLAYER_REFERENCE_LOAD',
  API_FIREBIRD_PLAYER_REFERENCE_SUCCESS: "API_FIREBIRD_PLAYER_REFERENCE_SUCCESS",

  //Registration Other Info Reference List
  API_REGISTRATION_OTHER_INFO_REFERENCE_LOAD: 'API_REGISTRATION_OTHER_INFO_REFERENCE_LOAD',
  API_REGISTRATION_OTHER_INFO_REFERENCE_SUCCESS: "API_REGISTRATION_OTHER_INFO_REFERENCE_SUCCESS",

  //Country Reference List
  API_COUNTRY_REFERENCE_LOAD: 'API_COUNTRY_REFERENCE_LOAD',
  API_COUNTRY_REFERENCE_SUCCESS: "API_COUNTRY_REFERENCE_SUCCESS",

  //Natiionality List
  API_NATIONALITY_REFERENCE_LOAD: 'API_NATIONALITY_REFERENCE_LOAD',
  API_NATIONALITY_REFERENCE_SUCCESS: "API_NATIONALITY_REFERENCE_SUCCESS",

  //HeardBy List
  API_HEARDBY_REFERENCE_LOAD: 'API_HEARDBY_REFERENCE_LOAD',
  API_HEARDBY_REFERENCE_SUCCESS: "API_HEARDBY_REFERENCE_SUCCESS",

  ///save end user registration
  API_SAVE_END_USER_REGISTRATION_LOAD: "API_SAVE_END_USER_REGISTRATION_LOAD",
  API_SAVE_END_USER_REGISTRATION_SUCCESS: "API_SAVE_END_USER_REGISTRATION_SUCCESS",

  ///Organisation Registration Registration Settings
  API_ORG_REGISTRATION_REG_SETTINGS_LOAD: "API_ORG_REGISTRATION_REG_SETTINGS_LOAD",
  API_ORG_REGISTRATION_REG_SETTINGS_SUCCESS: "API_ORG_REGISTRATION_REG_SETTINGS_SUCCESS",

  ///End User Registration Membership Products 
  API_MEMBERSHIP_PRODUCT_END_USER_REG_LOAD: "API_MEMBERSHIP_PRODUCT_END_USER_REG_LOAD",
  API_MEMBERSHIP_PRODUCT_END_USER_REG_SUCCESS: "API_MEMBERSHIP_PRODUCT_END_USER_REG_SUCCESS",

  ///Api End User Registration Failed
  API_END_USER_REGISTRATION_FAIL: "API_END_USER_REGISTRATION_FAIL",
  API_END_USER_REGISTRATION_ERROR: "API_END_USER_REGISTRATION_ERROR",

  UPDATE_END_USER_REGISTRATION: "UPDATE_END_USER_REGISTRATION",

  //Gender Reference List
  API_GENDER_REFERENCE_LOAD: 'API_GENDER_REFERENCE_LOAD',
  API_GENDER_REFERENCE_SUCCESS: "API_GENDER_REFERENCE_SUCCESS",

  //Player Position Reference 
  API_PLAYER_POSITION_REFERENCE_LOAD: 'API_PLAYER_POSITION_REFERENCE_LOAD',
  API_PLAYER_POSITION_REFERENCE_SUCCESS: "API_PLAYER_POSITION_REFERENCE_SUCCESS",

  /// get particular user organisation
  API_GET_USER_ORGANISATION_LOAD: "API_GET_USER_ORGANISATION_LOAD",
  API_GET_USER_ORGANISATION_SUCCESS: "API_GET_USER_ORGANISATION_SUCCESS",


  API_USER_REGISTRATION_GET_USER_INFO_LOAD: "API_USER_REGISTRATION_GET_USER_INFO_LOAD",
  API_USER_REGISTRATION_GET_USER_INFO_SUCCESS: "API_USER_REGISTRATION_GET_USER_INFO_SUCCESS",

  //Disability Reference List
  API_DISABILITY_REFERENCE_LOAD: 'API_DISABILITY_REFERENCE_LOAD',
  API_DISABILITY_REFERENCE_SUCCESS: "API_DISABILITY_REFERENCE_SUCCESS",

  REGISTRATION_CLEAR_DATA: "REGISTRATION_CLEAR_DATA",

  API_LIVE_SCORE_GET_FIXTURE_COMP_LOAD: "API_LIVE_SCORE_GET_FIXTURE_COMP_LOAD",
  API_LIVE_SCORE_GET_FIXTURE_COMP_SUCCESS: "API_LIVE_SCORE_GET_FIXTURE_COMP_SUCCESS",
  API_LIVE_SCORE_GET_FIXTURE_COMP_FAIL: "API_LIVE_SCORE_GET_FIXTURE_COMP_FAIL",
  API_LIVE_SCORE_GET_FIXTURE_COMP_ERROR: "API_LIVE_SCORE_GET_FIXTURE_COMP_ERROR",


  //// Live score only division 
  API_LIVE_SCORE_ONLY_DIVISION_LOAD: "API_LIVE_SCORE_ONLY_DIVISION_LOAD",
  API_LIVE_SCORE_ONLY_DIVISION_SUCCESS: "API_LIVE_SCORE_ONLY_DIVISION_SUCCESS",
  API_LIVE_SCORE_ONLY_DIVISION_FAIL: "API_LIVE_SCORE_ONLY_DIVISION_FAIL",
  API_LIVE_SCORE_ONLY_DIVISION_ERROR: "API_LIVE_SCORE_ONLY_DIVISION_ERROR",


  API_LIVE_SCORE_ROUND_LIST_LOAD: "API_LIVE_SCORE_ROUND_LIST_LOAD",
  API_LIVE_SCORE_ROUND_LIST_SUCCESS: "API_LIVE_SCORE_ROUND_LIST_SUCCESS",

  API_CLEAR_ROUND_DATA: "API_CLEAR_ROUND_DATA",
  API_LIVE_SCORE_CLEAR_LADDER: "API_LIVE_SCORE_CLEAR_LADDER",


  /////stripe payment API
  API_STRIPE_API_FAIL: "API_STRIPE_API_FAIL",
  API_STRIPE_API_ERROR: "API_STRIPE_API_ERROR",

  API_GET_INVOICE_LOAD: "API_GET_INVOICE_LOAD",
  API_GET_INVOICE_SUCCESS: "API_GET_INVOICE_SUCCESS",
  //////onchange charity roundup data
  API_ONCHANGE_CHARITY_ROUNDUP_DATA_DATA: "API_ONCHANGE_CHARITY_ROUNDUP_DATA_DATA",

  //invoice save post api
  API_SAVE_INVOICE_LOAD: "API_SAVE_INVOICE_LOAD",
  API_SAVE_INVOICE_SUCCESS: "API_SAVE_INVOICE_SUCCESS",

  ////get invoice status
  API_GET_INVOICE_STATUS_LOAD: "API_GET_INVOICE_STATUS_LOAD",
  API_GET_INVOICE_STATUS_SUCCESS: "API_GET_INVOICE_STATUS_SUCCESS",

  UPDATE_REGISTRATION_SETTINGS: "UPDATE_REGISTRATION_SETTINGS",

  UPDATE_TEAM_ACTION: "UPDATE_TEAM_ACION",

  //Disability Reference List
  API_PERSON_REGISTERING_ROLE_REFERENCE_LOAD: 'API_PERSON_REGISTERING_ROLE_REFERENCE_LOAD',
  API_PERSON_REGISTERING_ROLE_REFERENCE_SUCCESS: "API_PERSON_REGISTERING_ROLE_REFERENCE_SUCCESS",

  UPDATE_YOUR_INFO_ACTION: "UPDATE_YOUR_INFO_ACION",

  API_GET_INVITED_TEAM_REG_INFO_LOAD: "API_GET_INVITED_TEAM_REG_INFO_LOAD",
  API_GET_INVITED_TEAM_REG_INFO_SUCCESS: "API_GET_INVITED_TEAM_REG_INFO_SUCCESS",

  UPDATE_TEAM_PARENT_INFO: "UPDATE_TEAM_PARENT_INFO",

  UPDATE_TEAM_REG_SETTINGS: "UPDATE_TEAM_REG_SETTINGS",

  ///save end user registration
  API_UPDATE_TEAM_REGISTRATION_INIVTE_LOAD: "API_UPDATE_TEAM_REGISTRATION_INIVTE_LOAD",
  API_UPDATE_TEAM_REGISTRATION_INIVTE_SUCCESS: "API_UPDATE_TEAM_REGISTRATION_INIVTE_SUCCESS",

  // User Module Personal Details
  API_USER_MODULE_PERSONAL_DETAIL_SUCCESS: "API_USER_MODULE_PERSONAL_DETAIL_SUCCESS",
  API_USER_MODULE_PERSONAL_DETAIL_LOAD: "API_USER_MODULE_PERSONAL_DETAIL_LOAD",

  // User Module Medical Info
  API_USER_MODULE_MEDICAL_INFO_SUCCESS: "API_USER_MODULE_MEDICAL_INFO_SUCCESS",
  API_USER_MODULE_MEDICAL_INFO_LOAD: "API_USER_MODULE_MEDICAL_INFO_LOAD",

  // User Module Activity Player
  API_USER_MODULE_ACTIVITY_PLAYER_SUCCESS: "API_USER_MODULE_ACTIVITY_PLAYER_SUCCESS",
  API_USER_MODULE_ACTIVITY_PLAYER_LOAD: "API_USER_MODULE_ACTIVITY_PLAYER_LOAD",

  // User Module Activity Parent
  API_USER_MODULE_ACTIVITY_PARENT_SUCCESS: "API_USER_MODULE_ACTIVITY_PARENT_SUCCESS",
  API_USER_MODULE_ACTIVITY_PARENT_LOAD: "API_USER_MODULE_ACTIVITY_PARENT_LOAD",

  // User Module Activity Scorer
  API_USER_MODULE_ACTIVITY_SCORER_SUCCESS: "API_USER_MODULE_ACTIVITY_SCORER_SUCCESS",
  API_USER_MODULE_ACTIVITY_SCORER_LOAD: "API_USER_MODULE_ACTIVITY_SCORER_LOAD",

  // User Module Activity Manager
  API_USER_MODULE_ACTIVITY_MANAGER_SUCCESS: "API_USER_MODULE_ACTIVITY_MANAGER_SUCCESS",
  API_USER_MODULE_ACTIVITY_MANAGER_LOAD: "API_USER_MODULE_ACTIVITY_MANAGER_LOAD",

  API_USER_MODULE_PERSONAL_BY_COMPETITION_LOAD: "API_USER_MODULE_PERSONAL_BY_COMPETITION_LOAD",
  API_USER_MODULE_PERSONAL_BY_COMPETITION_SUCCESS: "API_USER_MODULE_PERSONAL_BY_COMPETITION_SUCCESS",

  API_USER_MODULE_REGISTRATION_LOAD: "API_USER_MODULE_REGISTRATION_LOAD",
  API_USER_MODULE_REGISTRATION_SUCCESS: "API_USER_MODULE_REGISTRATION_SUCCESS",

  ////Update Edit User Data
  API_USER_PROFILE_UPDATE_LOAD: "API_USER_PROFILE_UPDATE_LOAD",
  API_USER_PROFILE_UPDATE_SUCCESS: "API_USER_PROFILE_UPDATE_SUCCESS",

  ////Get Terms and Condition
  API_GET_TERMS_AND_CONDITION_LOAD: "API_GET_TERMS_AND_CONDITION_LOAD",
  API_GET_TERMS_AND_CONDITION_SUCCESS: "API_GET_TERMS_AND_CONDITION_SUCCESS",

  ////Get Registration Product Fees
  API_GET_REGISTRATION_PRODUCT_FEES_LOAD: "API_GET_REGISTRATION_PRODUCT_FEES_LOAD",
  API_GET_REGISTRATION_PRODUCT_FEES_SUCCESS: "API_GET_REGISTRATION_PRODUCT_FEES_SUCCESS",

  // User Module Activity Manager
  API_USER_MODULE_HISTORY_SUCCESS: "API_USER_MODULE_HISTORY_SUCCESS",
  API_USER_MODULE_HISTORY_LOAD: "API_USER_MODULE_HISTORY_LOAD",
  // Update Deregistration data
  API_UPDATE_DE_REGISTRATION: "API_UPDATE_DE_REGISTRATION",

  ////// shop product
  API_SHOP_PRODUCT_FAIL: "API_SHOP_PRODUCT_FAIL",
  API_SHOP_PRODUCT_ERROR: "API_SHOP_PRODUCT_ERROR",

  //////product listing get API 
  API_GET_SHOP_PRODUCT_LISTING_LOAD: "API_GET_SHOP_PRODUCT_LISTING_LOAD",
  API_GET_SHOP_PRODUCT_LISTING_SUCCESS: "API_GET_SHOP_PRODUCT_LISTING_SUCCESS",

  //////get reference type in the add product screen
  API_GET_TYPES_LIST_IN_ADD_PROUCT_LOAD: "API_GET_TYPES_LIST_IN_ADD_PROUCT_LOAD",
  API_GET_TYPES_LIST_IN_ADD_PROUCT_SUCCESS: "API_GET_TYPES_LIST_IN_ADD_PROUCT_SUCCESS",

  //////product details on id API
  API_SHOP_GET_PRODUCT_DETAILS_BY_ID_LOAD: "API_SHOP_GET_PRODUCT_DETAILS_BY_ID_LOAD",
  API_SHOP_GET_PRODUCT_DETAILS_BY_ID_SUCCESS: "API_SHOP_GET_PRODUCT_DETAILS_BY_ID_SUCCESS",
  /////clearing particular reducer data
  SHOP_PRODUCT_CLEARING_REDUCER_DATA: "SHOP_PRODUCT_CLEARING_REDUCER_DATA",

  /////add to cart post api
  API_SHOP_POST_ADD_TO_CART_LOAD: "API_SHOP_POST_ADD_TO_CART_LOAD",
  API_SHOP_POST_ADD_TO_CART_SUCCESS: "API_SHOP_POST_ADD_TO_CART_SUCCESS",
  ////Get Registration Review 
  API_GET_REGISTRATION_REVIEW_LOAD: "API_GET_REGISTRATION_REVIEW_LOAD",
  API_GET_REGISTRATION_REVIEW_SUCCESS: "API_GET_REGISTRATION_REVIEW_SUCCESS",

  ////Save Registration Review 
  API_SAVE_REGISTRATION_REVIEW_LOAD: "API_SAVE_REGISTRATION_REVIEW_LOAD",
  API_SAVE_REGISTRATION_REVIEW_SUCCESS: "API_SAVE_REGISTRATION_REVIEW_SUCCESS",

  UPDATE_REVIEW_INFO: "UPDATE_REVIEW_INFO",

  ////Get Registration Review Product
  API_GET_REGISTRATION_REVIEW_PRODUCT_LOAD: "API_GET_REGISTRATION_REVIEW_PRODUCT_LOAD",
  API_GET_REGISTRATION_REVIEW_PRODUCT_SUCCESS: "API_GET_REGISTRATION_REVIEW_PRODUCT_SUCCESS",

  ////Save Registration Review 
  API_SAVE_REGISTRATION_REVIEW_PRODUCT_LOAD: "API_SAVE_REGISTRATION_REVIEW_PRODUCT_LOAD",
  API_SAVE_REGISTRATION_REVIEW_PRODUCT_SUCCESS: "API_SAVE_REGISTRATION_REVIEW_PRODUCT_SUCCESS",

  UPDATE_REVIEW_PRODUCT: "UPDATE_REVIEW_PRODUCT",

  ////Get Registration By Id
  API_GET_REGISTRATION_BY_ID_LOAD: "API_GET_REGISTRATION_BY_ID_LOAD",
  API_GET_REGISTRATION_BY_ID_SUCCESS: "API_GET_REGISTRATION_BY_ID_SUCCESS",

  ///Validate Discount code
  API_VALIDATE_DISCOUNT_CODE_LOAD: "API_VALIDATE_DISCOUNT_CODE_LOAD",
  API_VALIDATE_DISCOUNT_CODE_SUCCESS: "API_VALIDATE_DISCOUNT_CODE_SUCCESS",

  ////Team name duplicate check
  TEAM_NAME_CHECK_VALIDATION_LOAD: "TEAM_NAME_CHECK_VALIDATION_LOAD",
  TEAM_NAME_CHECK_VALIDATION_SUCCESS: "TEAM_NAME_CHECK_VALIDATION_SUCCESS",

  // ////Get Team Registration Review 
  // API_GET_TEAM_REGISTRATION_REVIEW_LOAD: "API_GET_TEAM_REGISTRATION_REVIEW_LOAD",
  // API_GET_TEAM_REGISTRATION_REVIEW_SUCCESS: "API_GET_TEAM_REGISTRATION_REVIEW_SUCCESS",

  ////Save Registration Review 
  API_SAVE_TEAM_INVITE_REVIEW_LOAD: "API_SAVE_TEAM_INVITE_REVIEW_LOAD",
  API_SAVE_TEAM_INVITE_REVIEW_SUCCESS: "API_SAVE_TEAM_INVITE_REVIEW_SUCCESS",

  UPDATE_TEAM_REVIEW_INFO: "UPDATE_TEAM_REVIEW_INFO",

  ////Clear User Registration Without Root Participant
  USER_REGISTRATION_CLEAR_DATA: "USER_REGISTRATION_CLEAR_DATA",

  // Get Deregistration data
  API_GET_DE_REGISTRATION_LOAD: "API_GET_DE_REGISTRATION_LOAD",
  API_GET_DE_REGISTRATION_SUCCESS: "API_GET_DE_REGISTRATION_SUCCESS",

  // Save Deregistration data
  API_SAVE_DE_REGISTRATION_LOAD: "API_SAVE_DE_REGISTRATION_LOAD",
  API_SAVE_DE_REGISTRATION_SUCCESS: "API_SAVE_DE_REGISTRATION_SUCCESS",

  ///Api DeRegister Failed
  API_DE_REGISTER_FAIL: "API_DE_REGISTER_FAIL",
  API_DE_REGISTER_ERROR: "API_DE_REGISTER_ERROR",

  API_GET_YEAR_LISTING_LOAD: "API_GET_YEAR_LISTING_LOAD",
  API_GET_YEAR_LISTING_SUCCESS: "API_GET_YEAR_LISTING_SUCCESS",


  //New user registration design

  UPDATE_USER_REGISTATION_OBJECT: "UPDATE_USER_REGISTATION_OBJECT",
  SELECT_PARTICIPANT: "SELECT_PARTICIPANT",

  API_GET_PARTICIPANT_BY_ID_LOAD: "API_GET_PARTICIPANT_BY_ID_LOAD",
  API_GET_PARTICIPANT_BY_ID_SUCCESS: "API_GET_PARTICIPANT_BY_ID_SUCCESS",

  API_SAVE_PARTICIPANT_LOAD: "API_SAVE_PARTICIPANT_LOAD",
  API_GET_PARTICIPANT_SUCCESS: "API_SAVE_PARTICIPANT_SUCCESS",

  UPDATE_PARTICIPANT_COMPETITION_OBJECT: "UPDATE_PARTICIPANT_COMPETITION_OBJECT",

  ////Delete Registration Product 
  API_DELETE_REGISTRATION_PRODUCT_LOAD: "API_DELETE_REGISTRATION_PRODUCT_LOAD",
  API_DELETE_REGISTRATION_PRODUCT_SUCCESS: "API_DELETE_REGISTRATION_PRODUCT_SUCCESS",

  ////Delete Registration Participant 
  API_DELETE_REGISTRATION_PARTICIPANT_LOAD: "API_DELETE_REGISTRATION_PARTICIPANT_LOAD",
  API_DELETE_REGISTRATION_PARTICIPANT_SUCCESS: "API_DELETE_REGISTRATION_PARTICIPANT_SUCCESS",

  UPDATE_USER_REGISTRATION_STATE_VAR: "UPDATE_USER_REGISTRATION_STATE_VAR",

  API_IDENTIFICATION_REFERENCE_LOAD: "API_IDENTIFICATION_REFERENCE_LOAD",
  API_IDENTIFICATION_REFERENCE_SUCCESS: "API_IDENTIFICATION_REFERENCE_SUCCESS",

  API_OTHER_SPORTS_REFERENCE_LOAD: "API_OTHER_SPORTS_REFERENCE_LOAD",
  API_OTHER_SPORTS_REFERENCE_SUCCESS: "API_OTHER_SPORTS_REFERENCE_SUCCESS",

  UPDATE_PARTICIPANT_ADDITIONAL_INFO: "UPDATE_PARTICIPANT_ADDITIONAL_INFO",

  API_ACCREDITATION_UMPIRE_REFERENCE_LOAD: "API_ACCREDITATION_UMPIRE_REFERENCE_LOAD",
  API_ACCREDITATION_UMPIRE_REFERENCE_SUCCESS: "API_ACCREDITATION_UMPIRE_REFERENCE_SUCCESS",

  API_ACCREDITATION_COACH_REFERENCE_LOAD: "API_ACCREDITATION_COACH_REFERENCE_LOAD",
  API_ACCREDITATION_COACH_REFERENCE_SUCCESS: "API_ACCREDITATION_COACH_REFERENCE_SUCCESS",

  API_WALKING_NETBALL_QUES_REFERENCE_LOAD: "API_WALKING_NETBALL_QUES_REFERENCE_LOAD",
  API_WALKING_NETBALL_QUES_REFERENCE_SUCCESS: "API_WALKING_NETBALL_QUES_REFERENCE_SUCCESS",

  API_GET_SCHOOLS_LOAD: "API_GET_SCHOOLS_LOAD",
  API_GET_SCHOOLS_SUCCESS: "API_GET_SCHOOLS_SUCCESS" ,

  ////Get Registration Products Shop
  API_GET_REGISTRATION_SHOP_PRODUCTS_LOAD: "API_GET_REGISTRATION_SHOP_PRODUCTS_LOAD",
  API_GET_REGISTRATION_SHOP_PRODUCTS_SUCCESS: "API_GET_REGISTRATION_SHOP_PRODUCTS_SUCCESS",

  ////Get Registration Participant Users
  API_GET_REGISTRATION_PARTICIPANT_USERS_LOAD: "API_GET_REGISTRATION_PARTICIPANT_USERS_LOAD",
  API_GET_REGISTRATION_PARTICIPANT_USERS_SUCCESS: "API_GET_REGISTRATION_PARTICIPANT_USERS_SUCCESS",

  ////Get Registration Participant Address
  API_GET_REGISTRATION_PARTICIPANT_ADDRESS_LOAD: "API_GET_REGISTRATION_PARTICIPANT_ADDRESS_LOAD",
  API_GET_REGISTRATION_PARTICIPANT_ADDRESS_SUCCESS: "API_GET_REGISTRATION_PARTICIPANT_ADDRESS_SUCCESS",

  ////Get Registration Products Shop Pickup address
  API_GET_REGISTRATION_SHOP_PICKUP_ADDRESS_LOAD: "API_GET_REGISTRATION_SHOP_PICKUP_ADDRESS_LOAD",
  API_GET_REGISTRATION_SHOP_PICKUP_ADDRESS_SUCCESS: "API_GET_REGISTRATION_SHOP_PICKUP_ADDRESS_SUCCESS",

  //Get expired registration
  API_EXPIRED_REGISTRATION_LOAD: "API_EXPIRED_REGISTRATION_LOAD",
  API_EXPIRED_REGISTRATION_SUCCESS: "API_EXPIRED_REGISTRATION_SUCCESS",

  // Get Transfer Competition 
  API_GET_TRANSFER_COMPETITIONS_LOAD: "API_GET_TRANSFER_COMPETITIONS_LOAD",
  API_GET_TRANSFER_COMPETITIONS_SUCCESS: "API_GET_TRANSFER_COMPETITIONS_SUCCESS",

  //Team registration
  API_MEMBERSHIP_PRODUCT_TEAM_REG_LOAD: "API_MEMBERSHIP_PRODUCT_TEAM_REG_LOAD",
  API_MEMBERSHIP_PRODUCT_TEAM_REG_SUCCESS: "API_MEMBERSHIP_PRODUCT_TEAM_REG_SUCCESS",
  SELECT_TEAM: "SELECT_TEAM",
  UPDATE_TEAM_REGISTRATION_OBJECT: "UPDATE_TEAM_REGISTRATION_OBJECT",
  UPDATE_TEAM_REGISTRATION_STATE_VAR: "UPDATE_TEAM_REGISTRATION_STATE_VAR",
  UPDATE_REGISTRATION_TEAM_MEMBER_ACTION: "UPDATE_REGISTRATION_TEAM_MEMBER_ACTION",
  API_ORG_TEAM_REGISTRATION_SETTINGS_LOAD: "API_ORG_TEAM_REGISTRATION_SETTINGS_LOAD",
  API_ORG_TEAM_REGISTRATION_SETTINGS_SUCCESS: "API_ORG_TEAM_REGISTRATION_SETTINGS_SUCCESS",
  API_SAVE_TEAM_LOAD: "API_SAVE_TEAM_LOAD",
  API_SAVE_TEAM_SUCCESS: "API_SAVE_TEAM_SUCCESS",
  UPDATE_TEAM_ADDITIONAL_INFO: "UPDATE_TEAM_ADDITIONAL_INFO",
  API_GET_TEAM_BY_ID_LOAD: "API_GET_TEAM_BY_ID_LOAD",
  API_GET_TEAM_BY_ID_SUCCESS: "API_GET_TEAM_BY_ID_SUCCESS",
  API_GET_EXISTING_TEAM_BY_ID_LOAD: "API_GET_EXISTING_TEAM_BY_ID_LOAD",
  API_GET_EXISTING_TEAM_BY_ID_SUCCESS: "API_GET_EXISTING_TEAM_BY_ID_SUCCESS",
  API_EXPIRED_TEAM_REGISTRATION_LOAD: "API_EXPIRED_TEAM_REGISTRATION_LOAD",
  API_EXPIRED_TEAM_REGISTRATION_SUCCESS: "API_EXPIRED_TEAM_REGISTRATION_SUCCESS",

  API_GET_USER_ROLE_LOAD: "API_GET_USER_ROLE_LOAD",
  API_GET_USER_ROLE_SUCCESS: "API_GET_USER_ROLE_SUCCESS",

  API_GET_SCORER_ACTIVITY_LOAD: "API_GET_SCORER_ACTIVITY_LOAD",
  API_GET_SCORER_ACTIVITY_SUCCESS: "API_GET_SCORER_ACTIVITY_SUCCESS",

  API_GET_UMPIRE_ACTIVITY_LIST_LOAD: "API_GET_UMPIRE_ACTIVITY_LIST_LOAD",
  API_GET_UMPIRE_ACTIVITY_LIST_SUCCESS: "API_GET_UMPIRE_ACTIVITY_LIST_SUCCESS",
  API_GET_TEAM_REGISTRATION_INVITE_INFO_LOAD: "API_GET_TEAM_REGISTRATION_INVITE_INFO_LOAD",
  API_GET_TEAM_REGISTRATION_INVITE_INFO_SUCCESS: "API_GET_TEAM_REGISTRATION_INVITE_INFO_SUCCESS",
  UPDATE_INVITE_MEMBER_INFO_ACTION: "UPDATE_INVITE_MEMBER_INFO_ACTION",
  API_TEAM_INVITE_REG_SETTINGS_LOAD: "API_TEAM_INVITE_REG_SETTINGS_LOAD",
  API_TEAM_INVITE_REG_SETTINGS_SUCCESS: "API_TEAM_INVITE_REG_SETTINGS_SUCCESS",
  API_GET_INVITE_TEAM_REVIEW_PRODUCT_LOAD: "API_GET_INVITE_TEAM_REVIEW_PRODUCT_LOAD",
  API_GET_INVITE_TEAM_REVIEW_PRODUCT_SUCCESS: "API_GET_INVITE_TEAM_REVIEW_PRODUCT_SUCCESS",

  ///save stripe account
  API_SAVE_STRIPE_ACCOUNT_API_LOAD: "API_SAVE_STRIPE_ACCOUNT_API_LOAD",
  API_SAVE_STRIPE_ACCOUNT_API_SUCCESS: "API_SAVE_STRIPE_ACCOUNT_API_SUCCESS",


  API_GET_TEAM_INVITE_REVIEW_LOAD: "API_GET_TEAM_INVITE_REVIEW_LOAD",
  API_GET_TEAM_INVITE_REVIEW_SUCCESS: "API_GET_TEAM_INVITE_REVIEW_SUCCESS",

  API_GET_TEAM_INVITE_SHOP_PICKUP_ADDRESS_SUCCESS: "API_GET_TEAM_INVITE_SHOP_PICKUP_ADDRESS_SUCCESS",

  ////stripe login link
  API_GET_STRIPE_LOGIN_LINK_API_LOAD: "API_GET_STRIPE_LOGIN_LINK_API_LOAD",
  API_GET_STRIPE_LOGIN_LINK_API_SUCCESS: "API_GET_STRIPE_LOGIN_LINK_API_SUCCESS",

  API_GET_SEASONAL_CASUAL_FEES_LOAD: "API_GET_SEASONAL_CASUAL_FEES_LOAD",
  API_GET_SEASONAL_CASUAL_FEES_SUCCESS: "API_GET_SEASONAL_CASUAL_FEES_SUCCESS",

  API_GET_ALL_ORGANISATION_LIST_LOAD: "API_GET_ALL_ORGANISATION_LIST_LOAD",
  API_GET_ALL_ORGANISATION_LIST_SUCCESS: "API_GET_ALL_ORGANISATION_LIST_SUCCESS",
  API_GET_TEAM_SEASONAL_CASUAL_FEES_LOAD: "API_GET_TEAM_SEASONAL_CASUAL_FEES_LOAD",
  API_GET_TEAM_SEASONAL_CASUAL_FEES_SUCCESS: "API_GET_TEAM_SEASONAL_CASUAL_FEES_SUCCESS",

  // umpire uvailability get
  API_LIVE_SCORE_GET_UMPIRE_AVAILABILITY_LOAD: "API_LIVE_SCORE_GET_UMPIRE_AVAILABILITY_LOAD",
  API_LIVE_SCORE_GET_UMPIRE_AVAILABILITY_SUCCESS: "API_LIVE_SCORE_GET_UMPIRE_AVAILABILITY_SUCCESS",

  // umpire uvailability save
  API_LIVE_SCORE_SAVE_UMPIRE_AVAILABILITY_LOAD: "API_LIVE_SCORE_SAVE_UMPIRE_AVAILABILITY_LOAD",
  API_LIVE_SCORE_SAVE_UMPIRE_AVAILABILITY_SUCCESS: "API_LIVE_SCORE_SAVE_UMPIRE_AVAILABILITY_SUCCESS",

  API_LIVE_SCORE_UMPIRE_AVAILABILITY_FAIL: "API_LIVE_SCORE_UMPIRE_AVAILABILITY_FAIL",
  API_LIVE_SCORE_UMPIRE_AVAILABILITY_ERROR: "API_LIVE_SCORE_UMPIRE_AVAILABILITY_ERROR",

  ////Get Registration Products Shop Pickup address
  API_GET_REGISTRATION_SINGLE_GAME_LOAD: "API_GET_REGISTRATION_SINGLE_GAME_LOAD",
  API_GET_REGISTRATION_SINGLE_GAME_SUCCESS: "API_GET_REGISTRATION_SINGLE_GAME_SUCCESS",

  UPDATE_SINGLE_FEE: "UPDATE_SINGLE_FEE",
  API_FORGOT_PASSWORD_LOAD: "API_FORGOT_PASSWORD_LOAD",
  API_FORGOT_PASSWORD_SUCCESS: "API_FORGOT_PASSWORD_SUCCESS",

  UPDATE_PERSONAL_DATA_OBJECT: "UPDATE_PERSONAL_DATA_OBJECT",

  API_USER_PHOTO_UPDATE_LOAD: "API_USER_PHOTO_UPDATE_LOAD",
  API_USER_PHOTO_UPDATE_SUCCESS: "API_USER_PHOTO_UPDATE_SUCCESS"
  
};


export default ApiConstants;
