const AppConstants = {
  login: "Login",
  password: "Password",
  addAffiliate: "Add Affiliate",
  affiliatedTo: "Affiliated To",
  all: "All",
  organisationType: "Organisation Type",
  status: "Status",
  administrators: "Administrators",
  maintain: "Maintain",
  venueAndCourts: "Venues & Courts",
  affiliates: "Affiliates",
  affiliateApproveReject: "Affiliate - Approve / Reject",
  current: "Current",
  pendingForApproval: "Pending For Approval",
  club: "Club",
  peninsulaNetballAssociation: "Peninsula Netballl Association",
  name: "Name",
  address: "Address",
  phoneNumber: "Phone Number",
  contacts: "Contacts",
  ourOrganisation: "Our Organisation",
  dashboard: "Dashboard",
  affilatedTo: "Affiliated To",
  contact1: "Contact 1",
  contact2: "Contact 2",
  contact: "Contact ",
  title: "Title",
  email: "Email",
  mobile: "Mobile",
  permissionLevel: "Permission Level",
  remove: "Remove",
  addContact: "Add Contact",
  requestApproval: "Request for Approval",
  cancel: "Cancel",
  save: "Save",
  association: "Association",
  addAffiliates: "Add Affiliates",
  updateAffiliates: "Update",
  nsw: "NSW",
  add: "Add",
  postCode: "Postcode",
  enterPostCode: "Enter postcode",
  gender: "Gender",
  disability: "Disability",
  male: "Male",
  female: "Female",
  unspecified: "Unspecified",
  dob: "Date of Birth",
  competitionCategoty: "Competition Categoty",
  participant_firstName: "Participant First Name",
  participant_middleName: "Alternative or Middle Name",
  participant_lastName: "Participant Last Name",
  contactMobile: "Contact Mobile",
  contactEmail: "Contact Email",
  reenterEmail: "Re-enter Email",
  uploadPhoto: "Upload Photo",
  or: "or",
  takePhoto: "Take Photo",
  emergencyContactName: "Emergency Contact Name",
  emergencyContactMobile: "Emergency Contact Mobile",
  parents_guardians: "Parent/ Guardian Details",
  emergency_contact: "Emergency Contacts",
  firstName: "First Name",
  lastName: "Last Name",
  sameAddress: "Use same Address as Participant",
  useParentInfo: "Pre-populate Emergency Contact Info from Parent",
  linkExistingParent: "Link an existing parent",
  additionalInfoReqd: "Additional Information required",
  additionalPersonalInfoReqd: "Additional Personal Information required",
  haveYouEverPlayed: "Have you ever played Netball before:",
  yes: "Yes",
  no: "No",
  grade: "Grade",
  year: "Year",
  clubOther: "Club/other",
  lastCaptainName: "Name your last Captain",
  playWithFriend: "Play with a friend",
  referfriend: "Refer a friend",
  friend: "Friend",
  referfriend_friendLiketoPlay:
    "Refer a friend : Do you have a friend you think would like to play?",
  friendLiketoPlay: "Do you have a friend you think would like to play?",
  existingMedConditions: "Existing Medical Conditions",
  redularMedicalConditions: "Regular Medications",
  hearAbouttheCompition: "How did you hear about this Netball Competition?",
  who_fav_bird: "Who is your favourite Firebird?",
  consentForPhotos:
    "Do you give consent for photos to be taken and used for promotional purposes",
  addOtherReg: "Add Another Registration",
  favouriteTeam: "Favourite Netball Team",
  OtherInfoReqd: "Other information required",
  OtherParticipantReqd: "Other Participant information required",
  yourSupportImportant:
    "Your Support is important for the continued success of our Club. Can you help?",
  childrenCheckNumber: "Working with Children Check Number",
  childrenNumber: "Children Check Number",
  checkExpiryDate:"Check Expiry Date",									  
  childrenCheckNumberInfo:
    "Working with Children Check Number (You are required to have a working with Children Number. If you don’t have one you will need to apply.)",
  childCountry: "Which country were you born",
  childNationality: "What nationality are you",
  childLangSpoken: "Languages spoken at home",
  haveDisability: "Do you qualify for NDIS (National Disability Insurance Scheme)?",
  disabilityCareNumber: "Disability care Number",
  typeOfDisability: "Type of Disability",
  addanotherQuestion: "Add Another question",
  uniformAndMerchandise: "Uniforms and Merchandise",
  vouchers: "Vouchers",
  addvoucher: "Add voucher",

  //agreeTerm: "I have read and agree to (Affiliates name)  ",
  agreeTerm: "I have read and agree to all of the above Terms and Conditions  ",
  termsAndConditions: "Terms and Conditions",
  reviewOrder: "Review Order",
  checkOptions: "Checkout Options",
  voucherLink: "Voucher link",
  nearestCompetition: "Nearest Competition",
  photo: "Photo",
  addParent_guardian: "Add Parent/Guardian",
  addfriend: "Add Friend",

  usernamePasswordIncorrect:
    "Login Unsuccessful. Incorrect Username or Password",
  home: "Home",
  user: "User",
  registration: "Registration",
  competitions: "Competitions",
  liveScores: "Live Scores",
  events: "Events",
  shop: "Shop",
  umpires: "Umpires",
  incidents: "Incidents",
  finance: "Finance",
  totalRegistrations: "Total Registrations",
  totalUsers: "Total Users",
  edit: "Edit",
  familyDiscount: "Family Discount",
  netballRegistration:"Netball Registration",
  spring2019: "2019 Spring",
  membershipCategory: "Membership Category",
  netball: "Netball",
  winter2019: "2019 Winter",
  competition: "Competition",
  division: "Division",
  years12: "12 Years",
  addTimeSlot: "Add another time slot",
  saveDraft: "Save Draft",
  next: "Next",
  participateInComp: "Participating-In Competitions",
  ownedCompetitions: "Owned Competitions",
  addCompetition: "Add Competition",
  replicateCompetition: "Replicate Competition",
  draws: "Draws",
  venue: "Venue",
  round: "Round",
  saveAsDraft: "Save as Draft",
  publish: "Publish",
  registrationForm: "Registration Form",
  quickCompetition: "Quick Competition",
  quickCompetition3: "Competition Details (3/3)",
  quickCompetition2: "Teams & Players (2/3)",
  quickCompetition1: "Fixtures (1/3)",
  proposedTeamGrading: "Proposed Team Grading",
  proposedTeamGradingToggle: "Proposed Team Grading Toggle",
  ladder: "Ladder",
  competitionFormat: "Competition Format",
  tournament: "Tournament",
  weeklyCompetition: "Weekly Competition",
  knockOut: "Knock Out",
  roundRobin: "Round Robin",
  membershipProduct: "Membership Product",
  membershipProductTeam: "Membership Product - Team",
  membershipProductName: "Membership Product Name",
  validity: "Validity",
  calendarYear: "Calendar Year",
  twelveMonth: "12 months from registration",
  membershipTypes: "Membership Types",
  membershipTYpe: "Membership Type",
  player: "Player",
  mandatePlayerAge: "Mandate Player Age Restrictions",
  dob_from: "DOB-From",
  dob_To: "DOB-To",
  team: "Team",
  umpire: "Umpire",
  coach: "Coach",
  addMembershipType: "Add Membership Type",
  membershipFees: "Membership Fees",
  applyMembershipFee: "Apply Membership Fees to",
  casualFee: "Casual Fee",
  gst: "GST",
  seasonalFee: "Seasonal fee",
  type: "Type",
  reg_1_comp: "1st Competition Registration only",
  reg_all_comp: "All Competitions Registrations",
  reg_2_comp: "Discount 2nd Competition Registration",
  reg_3_comp: "Discount Seasonal Registration by Casual Fees paid",
  fees: "Fees",
  discount: "Discount Code",
  discounts: "Discounts",
  gernalDiscount: "General Discount",
  fixedAmount: "Fixed $ amount",
  percentageOff: "Percentage off",
  amount: "Amount",
  description: "Description",
  availableFrom: "Available From",
  availableTo: "Available To",
  discountCode: "Discount Code",
  code: "Code",
  earlyDiscount: "Early Discount",
  addChild: "Add Child",
  child1: "Child 1 %",
  child2: "Child 2 %",
  discountRename: "Discount (rename)",
  delete: "Delete",
  year2019: "2019",
  timeSlot: "Time Slots",
  timeBetweenGames: "Time between games",
  timeBetweenMatches: "Time between matches",
  mins: "mins",
  AbbottAddress: "Abbott Road Curl,Curl",
  save_publish: "Save & Publish",
  back: "Back",
  finals: "Finals",
  useDefault: " Use Default",
  finalFixtures: "Finals Fixture Template",
  matchType: "Match Type",
  quarters: "Quarters",
  matchDuration: "Match Duration",
  mainBreak: "Main Break",
  qtrBreak: "Qtr Break",
  betweenGames: "Between Games",
  assignManually: "Assign Manually",

  ///*****Competition Finals */
  rounds4Top16: "4 Rounds-Top 16",
  rounds3Top4: "3 Rounds-Top 4",
  rounds2Top3: "2 Rounds-Top 3",
  round1Top2: "1 Round-Top 2",
  customise: "Customise",
  extraTimeIfDraw1: "Extra time if a Draw - 1st Time",
  applyAllRounds: "Apply to all Rounds",
  applyAllSemiAndGrand: "Apply to Semi and Grand Final",
  applyGrandOnly: "Apply to Grand Final Only",
  extraTimeDuration: "Extra Time Duration",
  extraTimeMainBreak: "Extra Time Main Break",
  extraTimeBreak: "Extra Time Break",
  beaforeExtraTime: "Before Extra Time",
  extraTimeIfDraw2: "Extra time if a Draw - 2nd Time",
  oneGoalWins: "1st Goal Wins",
  twoGoalWins: "2nd Goal Wins",
  addAnotherFinalFormat: "Add Another Finals Format",
  setAsDefault: "Set as Default",
  applyFinalFormat: "Apply Final Format",
  //*****************Competition Fixtures */
  winterCompetition_7_8: "Winter Competition (7/8)",
  fixtures: "Fixtures",
  add_TimeSlot: "Add Timeslot",
  addCourt: "Add Court",

  //******************user Add Affiliates */
  All_communications: "All communications",
  competition_communcations: "Competitions communications",
  secretary: "Secretary",
  president: "President",

  //*****************Competition Format */
  competition_name: "Competition Name",
  use_default_competitionFormat: "Use default Competition Format Settings",
  standard_round_robin: "Standard Round Robin",
  double_round_robin: "Double Round Robin",
  halves: "Halves",
  quarters: 'Quarters',
  fixture_template: "Fixture Template",
  frequency: "Frequency",
  weekly: "Weekly",
  timeBetweenRounds: "Time between Rounds",
  days: "days",
  hours: "hours",
  applyMatchFormat: "Apply Match Format to",
  setUpFinalTemplate_optional: "Set Up Finals Template (Optional)",
  addNewCompetitionFormat: "Add New Competition Format",
  createDraftDraw: "Create Draft Draw",
  applyLadderFor: "Apply Ladder Format to",
  existingUserSelection: "Existing User Selection",

  /*******competition Ladder */
  mwnaPointScheme: "MWNA Points Scheme",
  applyLadderFormatTo: "Apply Ladder Format to",
  addNewLadderScheme: "Add New Ladder Scheme",
  useDefaultSettings: "Use default settings",
  ladderAdjustment: "Ladder Adjustment",
  addNewAdjustment: "Add new Adjustment",
  recalculateLadder: "Recalculate Ladder",
  finalise: "Finalise",
  ladderFormatScheme: "Ladder Point Scheme Name",

  /***competition matchSheet */
  matchSheets: "Match Sheets",
  teams: "Teams",
  gameTimeTracking: "Game Time Tracking",
  periods: "Periods",
  minutes: "Minutes",
  totalGames: "Total Games",
  positionTracking: "Position Tracking",
  shooting: "Shooting ",
  preview: "Preview",
  print: "Print",

  /**** competition Open Reg form*/
  competitionDetails: "Competition Details",
  competitionLogo: "Competition Logo",
  addShortNotes_registering: "Add a short note to those registering..",
  addVenue: " Add Venue",
  typeOfCompetition: "Type of Competition",
  numberOfRounds: "Number of Rounds",
  registration_close: "Registrations Close",
  close:"Close",			
  registration_type: "Registration Type",
  nonPlayingDates: "Non-Playing Dates",
  addAnotherNonPlayingDate: "Add Another Non Playing Date",
  addAnotherDivision: "Add Another Division",
  ageRestrictions: "Age Restrictions",
  mandateAgeRestrictions: "Mandate Age Restrictions",
  netSetGo: "NetSetGo",
  walkingNetball: "Walking Netball",
  socialNetball: "Social Netball",
  fastFive: "Fast Five",
  dobFrom: "DOB From",
  dobTo: "DOB To",
  gameSpecifics: "Game Specifics",
  playerInEachTeam: "Players in each team",
  minNumber: "Minimum Number",
  maxNumber: "Maximum Number",
  teams_in_each_grade_pool: "Teams in each grade/pool",
  registrationInvitees: "Registration Invitees",
  anyOrganisation: "Any organisation",
  direct: "Direct",
  notApplicable: " Not Applicable",
  percentageOff_FixedAmount: "Percentage off or Fixed Amount",
  governmentVouchers: "Government Vouchers",
  nswActiveKids: "NSW Active Kids",
  qldFairPlay: "Qld Fair Play",
  charityRoundUp: "Charity round up",
  roundTotheNearest$1: "Round to the nearest $1",
  roundTotheNearest$5: "Round to the nearest $5",
  roundTotheNearest$10: "Round to the nearest $10",
  /*******Competition Part Player grade calculate */
  playerGradingToggle: "Player Grading Toggle",
  playerGrading: "Player Grading",
  open: "Open",
  gradeAndNameTeams: "Grade and Name Teams",
  teamtoggle: "Team Toggle",
  submit: "Submit",
  final: "Final",
  addDivisions: "Add Divisions",
  addTeams: "Add Teams",
  winter_2019: "Winter 2019",
  how_Add_teams_players: "How will you add teams and players?",
  import: "Import",
  addManually: "Add Manually",
  Merge_ExistingCompetition: "Merge with an Existing Competition",
  inviteRegistration: "Invite Registrations",
  addCompetitionDetails: "Add Competition Details",
  SetUP_Template_Optional: "Set Up Finals Template (Optional) >",
  re_grading: "Re-grading",
  step1: "Step-1",
  step2: "Step-2",
  gradeToggle: "Grade Toggle",
  finalisedDraw: "Finalised Draw",
  confirm: "Confirm",
  replicateWhichCompetition: "Replicate which competition?",
  year2018: "2018",
  winter2018: "2018 Winter",
  newCompetitionName: "New Competition Name",
  competitionType: "Competition Type",
  startDate: "Start Date",
  endDate: "End Date",
  registrationFees: "Registration Fees",
  divisions: "Divisions",
  grades: "Grades",
  Venues_Courts: "Venues & Courts",
  competitionFormatGameTimes: "Competition Format & Game Times",
  review: "review",
  Step_3: "Step 3",
  contactNumber: "Contact Number",
  addAnotherCourt: "Add another court",
  addAnotherVenue: "Add another venue",
  venueAndTimes: "Venue And Times",
  Venue1: "Venue 1",
  club_TeamName: "Club/Team Name",
  game_Days: "Game Day(s)",
  dayOfTheWeek: "Day of the week",
  startTime: "Start Time",
  endTime: "End Time",
  addAnotherDay: "Add another day",
  courts: "Courts",
  lesHughesSportingComplex: "Les Hughes Sporting Complex",
  applyTo: "Apply to",
  courtPrioritisation: "Court Prioritisation",
  randomAllocation: "Random Allocation",
  automaticallyAssign_LowestCourt_highestGrade:
    "Automatically assign - lowest court  to highest grade",
  automaticallyAssign_LowestCourt_LowerGrade:
    "Automatically assign - lowest court to lowest grade",
  preferenceSettings: "Preference Settings",
  addAnother: "Add another",
  courtDetails: "Court Details",
  inbox: "Inbox",
  viewAll: "View All",
  eventsToday: "Events Today",
  competitionsOverview: "Competitions Overview",
  addNew: "Add New",
  participatingInCompetitions: "Participating In Competitions",
  playerProfile: "Player Profile",
  josefineMartinez: "Josefine Martinez",
  dateOfBirth: "Date of Birth",
  Date03032000: "03/03/2000",
  no0456765765: "0456 765 765",
  belrose08: "Belrose 08",
  activity: "Activity",
  statistics: "Statistics",
  personalDetails: "Personal Details",
  medical: "Medical",
  addAnotherDetail: "Add another detail",
  register: "Register",
  username: "Username",
  products: "Products",
  productDetails: "Product Details",
  playingMember: "Playing Member",
  nonPlayingMember: "Non Playing Member",
  Umpire_Referee: "Umpire/Referee",
  category: "Category",
  applicableTo: "Applicable to",
  level1_Affiliate_Associations: "1st level Affiliate - Associations",
  rename: "Rename",
  Level2_Affiliate_Clubs: "2nd Level Affiliate - Clubs",
  paymentFrequency: "Payment Frequency",
  oncePerYear: "Once Per Year",
  eachMatch: "Each Match",
  eachCompetition: "Each Competition",
  enterShortDescription: "Enter a short description of the product...",
  dob__From: "DOB - From",
  dob__To: "DOB - To",
  addGst10: "Add GST (10%)",
  clubFees: "Club Fees",
  associationFees: "Association Fees",
  stateFees: "State Fees",
  allFees: "All Fees",
  addAnotherVoucher: "Add Another Voucher",

  ///registartion membership fees list
  addMembershipProduct: "Add Membership Product",

  //comp court and times assign
  applyToAllVenues: "Apply to all venues",
  applySettingsToIndividualVenue: "Apply settings to individual venue",
  timeslotsAllocatedBasedOnGame: "Timeslots allocated based on game times",
  manuallyAddTimeslots: "Manually Add Timeslots",
  evenRotationTimeslots: "Even rotation of teams to timeslots",
  divisionAndGradeTimeslots: "Allocate Divisions and Grades to same timeslot",
  /*//registraion//*/
  addAFee: "Add a Fee",
  competitionFees: "Competition Fees",
  please_Sel_mem_pro: "Please select membership product",
  net_set_go: "Net Set Go",
  addDivision: "Add Division",
  allDivisions: "All Divisions",
  perDivision: "Per Division",
  paymentOptions: "Payment Options",
  organisationName: "Organisation Name",
  findAnotherCompetition: "Find Another Organisation or Competition",
  organisationLogo: "Organisation Logo",
  registrationOpen: "Registration Open",
  registrationLock: "Registration Lock",
  addMembershipCategory: "Add Membership Category",
  training: "Training",
  trainingVenue: "Training Venue",
  specialNote: "Special Note",
  replyToContactDetails: "Reply to contact details",
  role: "Role",
  phone: "Phone",
  how_users_Register: "How Users Register",
  app: "App",
  website: "Website",
  atEvent: "At event",
  advancedSettings: "Advanced Settings",
  shopIntegration: "Shop integration",
  ask_to_nominate: "Ask players to nominate two positions",
  disclaimers: "Disclaimers",
  addDisclaimer: "Add Disclaimer",
  disclaimerLink: "Disclaimer Link",
  addAnotherDisclaimerLink: "Add Another Disclaimer Link",
  openRegistrations: "Open Registrations",
  product: "Product",
  dOB: "DOB",
  year2020: "2020",
  year2017: "2017",
  year2016: "2016",
  registrationAccountSummary: "Registration Account Summary",
  paymentFor: "Payment For",
  dateFrom: "Date From ",
  dateTo: "Date To",
  umpireAllocation: "Umpire Allocation",
  users: "Users",
  ages: "Ages",
  roles: "Roles",
  genders: "Genders",
  alternate_location: "Alternative Location (outside 25km)",
  internet: "Internet",
  socialMedia: "Social Media",
  other: "Other",
  participant: "Participant",
  specialNotes: "Special Notes",
  contactDetails: "Contact Details",
  sunday: "Sunday",
  monday: "Monday",
  tuesday: "Tuesday",
  wednesday: "Wednesday",
  thursday: "Thursday",
  friday: "Friday",
  saturday: "Saturday",
  anyGradePreference: "Do you have any grade preference for courts?",
  rotateCourt: "Do you want to rotate courts",
  preferenceTimeSlot: "Do you have any grade preference for timeslots?",
  timeslotPreferences: "Timeslot preferences",
  courtPreferences: "Court preferences",
  homeTeamRotation: "Home Team Rotation",
  rotateTeam: "Rotate teams based on venue link",
  notRotateTeam: "Rotate teams without venue link",
  noRotation: "No rotation",
  drawPreferences: "Draw Preferences",
  mandateTeamAge: "Mandate Team Age Restrictions",
  mandateUmpireAge: "Mandate Umpire Age Restrictions",
  mandateCoachAge: "Mandate Coach Age Restrictions",
  details: "Details",
  membership: "Membership",
  payments: "Payments",
  general: "General",
  early: "Early",
  family: "Family",
  custom: "Custom",
  amountType: "Amount Type",
  addDiscount: "Add Discount",
  question: "Do you have a disability?",

  /////formik validation/////

  pleaseSelectCompetition: "Please select competition",
  pleaseSelectYear: "Please Select Year",
  select: "Select",
  trainingDaysAndTimes: "Training days and Times",
  // ******** Live Score Matches **********
  matchList: "Match List",
  addMatches: "Add Matches",
  export: "Export",
  import: "Import",
  matchName: "WSA 2 VS WSA 1",
  addMatch: "Add Match",
  date: "Date",
  divisionName: "Division Name",
  type: "Type",
  matchID: "mnbMatchId",
  homeTeam: "Home Team",
  awayTeam: "Away Team",
  umpire1Name: "Umpire 1 Name",
  enterUmpire1name: "Enter Umpire 1 Name",
  umpire2Name: "Umpire 2 Name",
  enterUmpire2name: "Enter Umpire 2 Name",
  umpire1Club: "Umpire 1 Club",
  umpire2Club: "Umpire 2 Club",
  scorer1: "Scorer 1",
  scorer2: "Scorer 2",
  umpireName: "Umpire Name",
  umpireClubName: "Umpire's Club Name",
  scorerName: "Scorer Name",
  score: "Score",
  players: "Players",

  addScorer: "Add Scorer",
  selectTeam: "Select Team",
  emailAdd: "Email Address",
  enterEmail: "Enter Email",
  contactNO: "Contact no",
  enterContactNo: "Enter valid contact number",
  scorers: "Scorers",

  addTeam: "Add Team",
  teamName: "Team Name",
  enterTeamName: "Enter team name",
  teamLogo: "Team Logo",
  selectComptition: "Select Competition",
  selectDivision: "Select Division",
  club_Association: "Club/Association/State Body",
  selectClub: "Select Club/Association/State Body",
  manager: "Manager",
  new: "New",
  exsiting: "Exisiting",
  teamList: "Team List",
  addPlayer: "Add Player",

  managersList: "Manager List",
  addManager: "Add Manager",
  importManager: "Import Manager",
  upload: "Upload",
  aboutManager: "About Manager",
  managerProfile: "Manager Profile",
  emailAddress: "email@gmail.com",
  teamManagers: "Team Manager",
  emailValue: "email@gmail.com",
  nameValue: "test score",
  contactValue: "9646097979",
  enter_firstName: "Enter first name",
  enterLastName: "Enter last name",
  assignToMatch: "Assign To Match",
  aboutScorer: "About Scorer",
  importMatch: "Import Match",
  fileInput: "File input",
  importTeam: "Import Team",
  exampleBlock: "Example block-level help text here.",
  noImage: "No Image",
  homeTeamFinalScore: "Home Team Final Score",
  awayTeamFinalScore: "Away Team Final Score",
  enterHomeTeamFinalScore: "Enter Home Team Final Score",
  enterAwayTeamFinalScore: "Enter Away Team Final Score",
  editMatch: "Edit Match",
  editTeam: "Edit Team",
  editManager: "Edit Manager",
  editScorer: "Edit Scorer",
  umpireList: "Umpire List",
  filterByDivision: "Filter By Division",
  competitionladders: "Competition Ladders",
  palyerList: "Player List",
  importPlayer: "Import Player",
  addPlayer: "Add Player",
  editPlayer: "Edit Player",
  profilePic: "Profile Picture",
  enterPlayerID: "Enter player id",
  playerId: "Player Id",
  shootingState: "Shooting Stats",
  incidentDetails: "Incident Detail",
  photos: "Photos",

  // 24-Jan
  forfiet: "Forfeit",
  abandon: "Abandon",
  endMatch: "End match",
  addNews: "Add News",
  editNews: "Edit News",
  newsTitle: "News Title",
  enterNewsTitle: "Enter News Title",
  newsBody: "News Body",
  author: "Author",
  enterAuthor: "Enter Author",
  recipients: "Recipients",
  selectRecipients: "Select Recipients",
  newsImage: "News Image",
  newsVideo: "News Video",
  newsExpiryDate: "News Expiry Date",
  newsExpiryTime: "News Expiry Time",
  newsDetail: "News Detail",
  settings: "Settings",
  sponsorshipBanners: "Sponsorship Banners",
  venues: "Venues",
  matchSettings: "Match Settings",
  wouldLikeRecord: "Would you like to record?",
  record: "Record",
  report: "Report",
  attendence_reord_report: "Attendance Recording and Reporting",
  scoring: "Scoring",
  single: "Single",
  timer: "Timer",
  ladderSettings: "Ladder Settings",
  publish_notify: "Publish and Notify",
  backToNews: "Back to all news",

  scorer: "Scorer",
  banners: "Banners",
  uploadImage: "Upload Image",
  selectImage: "Select Image",
  bannerlink: "Banner Link",
  removeBanner: "Remove Banner",
  showHomePage: "Show on Home Page",
  showonDrawsPage: "Show on Draws Page",
  showonLadderPage: "Show on Ladder Page",
  teamAttendane: "Team Attendance",
  newsList: "News List",
  gameTime: "Game Time",
  goalState: "Goal Statistics",
  bulkMatchChange: "Bulk Match Change",
  whatDoWantDO: "What do you want to do?",
  slectOption: "Select Option",
  whichMatchChange: "Which matches do you want to change?",
  matchOnDate: "Matches on this date",
  forTimeRange: "For this time range",
  byVenue: "By Venue (optional)",
  selectVenue: "Select Venue",
  hour: "Hours",
  seconds: "Seconds",
  toThisTime: "Or to this time",
  pushBack: "Push Back",
  court: "Court",
  selectCourt: "Select Court",
  endMatchs: "End Matches",
  selectresultType: "Select Result Type",
  round_1: "Round 1",
  round_2: "Round 2",
  selectRoundOne: "Select Round 1",
  selectRoundTwo: "Select Round 2",
  bringForward: "Bring forward",
  changeMatchCriteria: "Change matches with the following criteria",
  selectReason: "Select Reason",
  todaysMatch: "Today's Match",
  newsPost: "News Post",
  scorerProfile: 'Scorer Profile',
  managerSearch: 'Manager Search',
  affiliate: "Affiliate",
  selectAffiliate: "Select Affiliate",
  useClubLogo: 'Use Club Logo',
  activeNews: 'Active News',
  addNewRound: 'Add New Round',
  selectCourt: "Select Court",
  twoHalves: "TWO_HALVES",
  fourQuarters: "FOUR_QUARTERS",
  editBanners: 'Edit Banners',
  editBanner: 'Edit Banner',
  addBanners: 'Add Banners',
  ////export URl
  exportUrl: 'http://world-sport-action-socket.appspot.com/players/csv?competitionId=',

  ////Registartion
  membershipTypeName: "Membership Type Name",
  pleaseEnterMembershipTypeName: "Please Enter Membership Type Name",



  // venue new constants
  evenRotation: "Even rotation",
  allocateToSameCourt: 'Allocate to same court',
  noPreference: "No Preference",
  evenRotation: "Even rotation",
  allocateToSameCourt: 'Allocate to same court',
  noPreference: "No Preference",
  statringSaturday: "Starting Sat 08/02",
  anyGradePreference2: "Do you have any court preferences for divisions or grades?",
  timeSlotRotation: "TimeSlot rotation",
  proceedLowerGrade: "Precede lower grades with higher grades",

  saveAsDefault: "Save as Default",

  //time slot constants
  anyTimePreference: "Do you have any timeslot preferences for divisions or grades?",
  none: "None",
  timeslotsAllocatedBasedOnMatchs: "Timeslots allocated based on match duration",
  manuallyAddTimeslots: "Manually add timeslots",
  enterTimeMatchesEachDay: "Enter time matches should run each day",
  allocateToSametimeslot: "Allocate to same time slot",
  newCompetition: "New Competition",

  // team grading summary
  teamGradingSummary: "Team Grading Summary",
  addgrade: "Add Grade",

  //new changes in venue
  linkToHomeAffiliate: "Link to Home Affiliate",
  addressOne: "Address Line 1",
  addressTwo: "Address Line 2",
  suburb: "Suburb",
  state: "State",
  postcode: "Postcode",


  editCompetition: "Edit Competition",
  selectVenue: "Select Venue",


  /////live scores
  teamSearch: "Team Search",
  managerSearch: "Manager Search",
  scorerSearch: "Scorer Search",

  organisationTypeRefId: "organisationTypeRefId",
  affiliatedToOrgId: "affiliatedToOrgId",
  street1: "street1",
  street2: "street2",
  suburbField: "suburb",
  stateRefId: "stateRefId",
  middleName: "Middle Name",

  ////Team Grading
  finalTeamGrading: "Final Team Grading",

  existing: "Existing",

  ////Team Grading summary
  updateGradeName: "Update Grade Name",
  gradeName: "Grade Name",
  pleaseEnterGradeName: "Please enter grade name",

  ///livescores
  todaysIncidents: "Today's Incidents",
  todaysMatch: "Today's Matches",
  recipientSelection: "Enter Recipients",

  ////addedd 2 march
  ByMatch: "By Match",
  total: "Total",
  //End User Registration
  areYouRegisteringYourself: "Are you registering yourself as an individual?",
  whoAreYouRegistering: "Who are you registering?",
  child: "Child",
  team: "Team",
  whatTypeOfRegistration: "What type of registration?",
  nonPlayer: "Non Player",
  yesAsAPlayer: "Yes, as a Player",
  yesAsANonPlayer: "Yes, as a Non-Player",
  registeringSomeoneElse: "No, registering someone else",
  competitionMembershipProductDivision: "Competition, Membership Product and Division",
  participantDetails: "Participant Details",
  indicatePreferredPlayerPosition: "Indicate two preferred playing positions:",
  fullName: "Full Name",
  playWithFriendSubtitle: "We may be able to accommodate friends playing with each other. Please note, this is normally only available for lower graded teams. You can choose up to three friends.",
  addAnotherProduct: "ADD ANOTHER MEMBERSHIP PRODUCT",
  addAnotherParticipant: "Add Another Participant",
  favouriteTeamReference: "FavouriteTeam",
  firebirdPlayer: "FirebirdPlayer",
  registrationOtherInfo: "RegistrationOtherInfo",
  countryReference: "Country",
  nationalityReference: "Nationality",
  heardByReference: "HeardBy",
  playerPosition: "PlayerPosition",
  position1: "Preferred Position 1",
  position2: "Preferred Position 2",

  createTeam: "Create Team",
  unassigned: "Unassigned",
  organisation: "Organisation",
  gameTimeStatistics: "Game Time Statistics",
  searchManager: "Search Manager",
  divisionList: "Division List",


  /// add news

  notifyAgain: "Notify again",
  notify: "Notify",

  gradeName: "GradeName",
  editDivision: "Edit Division",

  divisionList: "Division List",
  voucherDeleteConfirmMsg: "Are you sure you want to delete this voucher?",
  productDeleteConfirmMsg: "Are you sure you want to delete this product?",
  participantDeleteConfirmMsg: "Are you sure you want to delete this participant?",
  registrationDeleteConfirmMsg: "Are you sure you want to delete this registration?",
  friendDeleteConfirmMsg: "Are you sure you want to delete this friend?",
  registrationOptionConfirmMsg: "Changing the registration type will clear the information you have entered already. Please confirm you wish to proceed.",
  parentDeleteConfirmMsg: "Are you sure you want to delete this parent?",
  areYouAnExistingUser: "Are you an existing user?",
  newUser: "New User",
  payment: "Payment",
  submitPayment: "Submit Payment",
  pay: "Pay",
  disput_description: "Result in dispute",
  draft_description: "Final result entered and unconfirmed",
  final_description: "Final result entered and confirmed",
  logo: "Logo",
  noInformationProvided: "No information provided",
  noPhotosAvailable: "No photos available",
  registrationType: "Registration Type",
  inviteIndividualTeamMember: "Invite Individual Team Members to Register and pay their portion of the Team Registration Fee",
  registerOnBehalf: "Register on behalf of the Team and pay the entire Team Registration Fee",
  areYouRegisteringAsPlayer: "Are you registering as a Player in this Team?",
  noRegisteringATeam: "No, registering a team",
  personRegisteringRole: "Person Registering Role",
  personRegRoleRef: "PersonRegisteringRole",
  addAnotherRegitration: "ADD ANOTHER REGISTRATION"	,
  yourInfo: "Your Info",
  teamRegisteringYourself: 	"Are you registering yourself",
  registeringPerson: "Registering Person",
  invitedTeamMember: "Invited Team Member",
  parentOrGuardianDetail: 'Parent/Guardian Details',
  emergencyContacts: 'Emergency Contacts',
  otherInformation: 'Other Information',
  countryOfBirth: 'Country of Birth',
  userProfile: 'User Profile',
  noDataAvailable: 'No Data Available',
  transfer: "Transfer",
  deRegistration: "De-registration",
  emailValidationInfo: "Updating the email address will update the login information(User Name) while submitting this form. Please ensure that the information provided is correct.",
  stateHeading: 'State',
  childDetails: "Child Details",
  registrationDivisions: "Registration Divisions",
  downloadTemplate: 'Download Template',
  playerImpMsg: "Import will remove existing Team Members from the list and populate the new Team Members based on the data available in the Template.",
  termsAndConditionsHeading: "Terms & Conditions",
  totalCasualFees: "Total Casual Fees",
  totalSeasonalFees: "Total Seasonal Fees",
  totalTeamFees: "Total Team Fees",
  includeGST: " (incl. GST)",
  history: "History",
  registrationChange: "Registration Change",
  mobileNumber: "Mobile Number",
  whatRegistrationChange: "What registration change do you",
  takenCourtforTraining: "Have you taken the court for training, grading or a competition game",
  reasonRegisterTitle: "Why would you like to de-register?",
  reasonForTransfer: "Reason for Transfer",
  directDebit: "Direct Debit",
  creditCard: "Credit/Debit Card",
  cash: "Cash",
  selectedPaymentOption: "Please select payment option Credit Card or Direct Debit",
  stripeMandate1: `By providing your bank account details and confirming this payment,
  you agree to this Direct Debit Request and the`,
  stripeMandate2: `, and authorise Stripe Payments Australia Pty Ltd ACN 160 180 343 Direct Debit User ID number 507156(“Stripe”) to debit your account through the Bulk Electronic Clearing System(BECS) on behalf of Stripe Press(the "Merchant") for any amounts separately communicated to you by the Merchant.You certify that you are either
  an account holder or an authorised signatory on the account listed
  above.`,
  shopIncomplete:"Shop - Incomplete",
  addToCart: "Add to cart",
  size: "Size",
  quantity: "Quantity",
  expiryDate:"Expiry Date",
  addedToCart:"Product added to cart",

  // RegistrationReviewForm 

  individualRegistration:"Individual Registration",
  participantName:"Participant Name",
  competitionName:"Competition Name",
  hyphen:" - ",
  less:"LESS",
  governmentSportVouchers:"Government Sports Vouchers - ",
  hardshipPlayer:"Hardship Player Discount",
  payAsYou:"Pay as You Go",
  gameVoucher:"Game Voucher",
  payfullAmount:"Pay Full Amount",
  weeklyInstalment:"Weekly Instalment",
  instalmentDates:"Instalment dates",
  schoolRegistration:"School Invoice",
  governmentSportsVoucher:"Government Sports Voucher",
  support:"Support",
  confidentGirlsFoundation:"Confident Girls Foundation",
  // review products 
  reviewProducts:"Review Products",
  subTotal:"Sub-total",
  shipping:"Shipping",
  charityRoundUp:"Charity Round-Up",
  totalPaymentDue:"Total Payment Due",
  securePaymentOptions:"Secure Payment Options",
  credit:"Credit",
  debitCard:"Debit Card",
  previous:"Previous",
  applyCode: "Apply Code",
  removeCode: "Remove Code",
  expiryDate:"Expiry Date",
  teamRegistration: "Team Registration",
  personRegistering: "Person Registering",
  webAdmin:"WebAdmin",
  teamAlreadyExists: "This team name is already in use. Please choose an alternative name.",
  singleCompetition: "Single Competition",
  registrationCode: "Registration Code",
  ok:"Ok"	,
  useSameEmailAsParent: "Use same email as parent",
  stateMismatchTitleMessage: "Warning",
  stateMismatchModelMessage: "You can only register for one state at a time. Your other selections will be cleared if you want to select a different state. Do you want to proceed?",
  CASUAL_FEE: 1,
  SEASONAL_FEE: 2,
  emailExp: "/^-?(0|[1-9][0-9]*)(\.[0-9]*)?$/",
  addressSearch:"Address Search",
    addressError: "Please select a address from the address search",
  toBeInvoicedViaSchool: "To be invoiced via school",
  userDetailsInvalid: "User Details Invalid",
  participants: "Participants",
  wouldYouLikeTopay:"How would you like to pay?",
  addDiscountCode:" Add Discount Code",
  addGovernmentVoucher:" Add Government Voucher",
  supportGirlsFoundation: 'Support - Confident Girls Foundation',
  girlsFoundationDescription:`Confident Girls Foundation works with grassroots service providers to develop and implement programs
  aimed at creating more opportunities for girls going through adversity. You can help us support them by
  choosing a donation option below.`,
  RoundUpAtLeast:"Round up at least",
  SorryNotAtTheMoment:"No, sorry not at the moment",
  continuedSuccessOfOurClub:"Your Support is important for the continued success of our Club. Can you help?",
  yourOrder:"Your order",
  ConditionsForNetballQLD:"Terms and Conditions for Netball QLD",
  continue:"Continue",

  //new registration form
 signupToCompetition: "Sign up to competition",
 participantDetails : "Participant Details",
 selectCompetition: "Select Competitions",
 additionalInformation: "Additional Information",
 addPariticipant: "Add a Participant",
 selectOrAddParticipant: "Select or Add a participant",
 newParticipant: "New Participant",
 addNewParticipant: "Add a new participant", 
 selectAnother: "Select Another",
 selectAddress: "Select Address",
 addNewAddress: "Add New Address",
 addNewParentGaurdian: "Add New Parent/Gaurdian",
 chooseMembershipProducts: "Choose Membership Product",
 uniform: "Uniform",
 referFriendSubTitle: "Do you have a friend you think would like to play?",
 findAnotherCompetition: "Find Another Competition",
 addAnotherCompetition: "Add Another Competition",
 additionalPersonalInformation: "Additional Personal Information",
 haveYouEverPlayed: "Have you ever played Netball before?" ,
 doYouHaveDisablity: "Do you have a disablity?",
 emergencyContact: "Emergency Contact",
 findACompetition: "Find a Competition",
 newParticipantRegistration: "New Participant Registration",
 newTeamRegistration: "New Team Registration",
 noRegisteringMyChild: "No, Registering my child",
 noRegisteringSomeoneElse: "No, Registering someone else",
 loginAndProceedRegistration: "LOGIN & PROCEED TO REGISTRATION",
 proceedToRegistration: "PROCEED TO REGISTRATION",
 forgotResetPassword: 'Forgot/ Reset Password',
 findAddress: "Find Address",
 enterAddressManually: "Enter Address Manually",
 country: "Country",
 newParentOrGuardian: "New Parent/Guardian",
 returnToAddressSearch: "Return to Address Search",
 enterAddress: "Enter Address",
 addCompetitionAndMembership: "Add Competition and Membership",
 signupToCompetition: "Sign up to Competition",
 merchandiseShop:"Merchandise Shop",
 selectColor:"Select color",
 vixensWarmUpShirt:"Vixens Warm Up Shirt",
 allCategories:"All categories",
 productDescription:`Get kitted out like your favourite players. As worn by the first
 team on matchdays, this short sleeve shirt is the perfect way
 to show your pride and passion.`,
 shippingOptions:"Shipping Options",
 netballQueenslandMerchandise:"Netball Queensland Merchandise",
 biloelaAssociationMerchandise:"Biloela Association Merchandise",
 Pickup:"Pickup",
 Delivery:"Delivery",
 deliveryAndBillingAddress:"Delivery and Billing Address",
 deliveryAddress:"Delivery Address",
 billingAddress:"Billing Address",
 useDifferentAddress:"Use a different address",
 deleteProductMsg: "Do you want to remove this product?",
 deleteParticipantMsg: "Do you want to remove this participant?",
 deleteCompetition: "Do you want to remove this competition?",
 whichCountryWereBorn: "In which country were you born?",
 doYouIdentifyAs: "Do you identify as: ",
 identifyAs: "IdentifyAs",
 injury: "Please list any injury which is current or recurring or requires surgery? ",
 anyInjury: "Any Injury",
 alergy: "Please detail any allergies (medical or food) or illnesses?",
 anyAlergies: "Any Alergies", 
 teamYouFollow: "Which Suncorp Super Netball Team do you follow?",
 otherSports: "otherSports",
 playingOtherParticipantSports: "Are you playing any other participation sport?",
 childPlayingOtherParticipantSports: "Is your child playing any other participation sport?",
 someOnePlayingOtherParticipantSports: "Are other playing any other participation sport?",
 firstYearPlayingNetball: "Is this your first year playing netball?",
 yearsOfPlaying: "Years of playing",
 schoolYouAttend: "Which school do you attend?",
 schoolYourChildAttend: "Which school does your child attend?",
 schoolSomeoneAttend: "Which school they attend?",
 yourChildSchoolGrade: "What school grade is your child in",
 yourSchoolGrade: "What school grade are you in",
 schoolGrade: "School Grade",
 participatedSchoolProgram: "Have you participated in the Sporting School Program?",
 accreditationUmpire: "accreditationUmpire",
 accreditationCoach: "accreditationCoach",
 nationalAccreditationLevelUmpire: "What is your national accreditation level (Umpire)?",
 nationalAccreditationLevelCoach: "What is your national accreditation level (Coach)?",
 newToUmpiring: "Are you new to Umpiring?",
 yourAssociationLevel: "What is your Association Level?",
 associationLevel: "Association Level",
 workingWithChildrenCheckNumber: "What is your Working with Children Check Number or BlueCard Number? You are required to have a Working with Children Check Number or BlueCard. If you don't you will need to apply for one.",
 haveCompletedPrerequisites: "Have you completed the prerequisites for a training Umpire?",
 walkingNetball: "WalkingNetball",
 useParentsEmailAddress: "Use parent's email address",
 returnToSelectAddress: "Return to select address",
 yourDetails: "Your Details",
 selectFromParticipantAndParentDetails: "Select from Participant and Parent Details",
 addNewDetails: "Add new Details",
 pickupAddress: "Pickup Address",
 qty: "Qty",
 securePaymentMsg: "There is no payment required",
 selectParentOrGuardian: "Select Parent/Guardian",
 returnToShoppingCart: "Return to Shopping Cart",
 anyExistingMedicalCondition: "Please detail any existing medical conditions, allergies (medical or food) or Illnesses. Please detail a Management Plan (if applicable)",
 anyRedularMedicalConditions: "Any Regular Medications?",
 registeringAs:  " Registering as :",
 search: "Search",
 admin: "Admin",
 teamDetails: "Team Details",
 teamMember: "Team Member",
 payingForMember: "I am paying for this member",
 addTeamMember: "Add Team Member",
 members: "Members",
 payingFor: "I am paying for",
 notPayingFor: "I am not paying for",
 umpireActivity:"Umpire Activity",
 uploadBankAccnt: "Upload Bank Account",
 editBankAccount: "Edit Bank Account",
 playerHeading: 'Player',
 managerHeading: 'Manager',
 scorerHeading: 'Scorer',
 ifAllTeamMemberHaveNotRegistered: "If all Team Members have not registered by the Competition start date, you will be charged any outstanding monies and it will be your responsibility to recoup that from your team members.",
 addDetails: "Add Details",
 showMoreInformation: "Show more Information",
 hide: "Hide",
 transactionFeeApplies: "A transaction fee of 2.25% applies.",
 transactionFee: "Transaction Fee",
 payInFull: "Pay in full",
 splitAmoingTeamMember: "Split amongst team members",
 liveScoreSeasonFixture:"LiveScore Season Fixture",
 dateTime:"Date/Time",
 matchResult:"Match Result",
 matchStatus:"Match Status",

 //Netball questions,
 haveHeartTrouble: "Has your doctor ever said you have heart trouble?",
 havePainInHeartOrChest: "Do you frequently have pains in your heart or chest?",
 haveSpellsOfServerDizziness: "Do you often feel faint or have spells of server dizziness?",
 hasBloodPressureHigh: "Has your doctor ever said your blood pressure is too high?",
 hasBoneProblems: "Do you have any joint or bone problem(s) that may be worsened with exercise?",
 whyShouldNotTakePhysicalActivity: "Do you know of any reason why you should not take part in physical activity?",
 pregnentInLastSixMonths: "Are you or have you been pregnant in the last 6 months?",
 sufferAnyProblems: "Do you suffer from any problems of the lower back?",

 provideFurtherDetails: "Please provide further details",
 walkingNetball2: "Walking Netball",
 pleaseSpecify: "Please Specify",
 yearsOfPlayingNetball: "How many years have you played Netball?",
 noCompetitionsForOrganisations: "There are no open competitions for this organisation",
 internationalCCMsg: "A Transaction fee of 3.0%+ 30c applies",
 backToHome: "Back to home",
 domesticCCMsg: "A Transaction fee of 2.25%+ 30c applies",
 directDebitMsg: "A transaction fee of 1.5% +30c applies (capped at $3.50).",
 creditCardMsg: "A transaction fee of 2.25% + 30c is charged for domestic credit cards and 3.0% + 30c for International. For American express cards a fee of 2.7% + 30c applies.",
 multpleRolesSelected:"(multiple roles can be selected)",
 membershipDetails:'Membership Details',
 competitionSpecifics:'Competition Specifics',
 totalsinglegamefees:'Total Single Game Fees'

};

export default AppConstants;
