const AppImages = {
  plusSign: require("../images/add.png"),
  transfer: require("../images/transfer.png"),
  moreTripleDot: require("../images/more.png"),
  activeRegist: require("../images/active-regist.svg"),
  playerDp: require("../images/dp.jpg"),
  calendar: require("../images/calendar.png"),
  callAnswer: require("../images/call-answer.png"),
  group: require("../images/group.png"),
  circleOutline: require("../images/circle-shape-outline.png"),
  redCross: require("../images/redcross.svg"),
  greenDot: require("../images/green_dot.png"),
  greyDot: require("../images/grey_dot.png"),
  redDot: require("../images/red_dot.png"),
  notFound404: require("../images/404.png"),
  netballLogo1: require("../images/logo1.png"),
  searchIcon: require("../images/search-icons.svg"),
  userImagedashboard: require("../images/dd.png"),
  homeIcon: require("../images/home.svg"),
  userIcon: require("../images/user.svg"),
  regIcon: require("../images/regist.svg"),
  compIcon: require("../images/competition.svg"),
  liveScoreIcon: require("../images/livescore.svg"),
  eventsIcon: require("../images/event.svg"),
  shopIcon: require("../images/shop.svg"),
  umpireIcon: require("../images/umpire.svg"),
  incidentIcon: require("../images/incident.svg"),
  financeIcon: require("../images/finance.svg"),
  circleImage: require("../images/circle-cropped.png"),
  export: require("../images/export.png"),
  import: require("../images/import.png"),
  commentEmpty: require("../images/chat-empty.png"),
  commentFilled: require("../images/chat-filled.png"),
  defaultUser: require("../images/default_user.png"),
  successTick: require("../images/success-tick.png"),
  purpleDot: require("../images/PurpleDot.png"),
  loginImage: require("../images/sign_in.jpg"),
  suceessImg: require("../images/shapes.png"),
  squareImage: require("../images/squareImage.png"),
  netballImages: require("../images/imagesNetball.png"),
  netballLogoMain: require("../images/netball.png"),
  printImage: require("../images/print.png"),
  removeIcon: require("../images/remove-icon.jpg"),
};

export default AppImages;
